# {{ project_name }} Configuration

app_name: {{ project_name }}

logging:
  level: DEBUG
  format: text

web:
  server:
    host: "127.0.0.1"
    port: 8000
  api_docs:
    enabled: true
    provider: both

db:
  backend:
    url: "sqlite:///./dev.db"
  pool:
    max_size: 5

cache:
  backends:
    - name: memory
      type: memory
      default: true
