from __future__ import annotations

# Admin-specific UI components stay imported from inside admin
from lexigram.admin.ui.htmx_attrs import HTMXAttrs, HTMXAttrsBuilder
from lexigram.admin.ui.molecules.date_range_filter import DateRangeFilter
from lexigram.admin.ui.molecules.filter_bar import FilterBar
from lexigram.admin.ui.molecules.filter_dropdown import FilterDropdown
from lexigram.admin.ui.molecules.jump_to_page import JumpToPage
from lexigram.admin.ui.molecules.page_size_selector import PageSizeSelector
from lexigram.admin.ui.molecules.pagination_links import PaginationLinks
from lexigram.admin.ui.observability import (
    get_health_status,
    log_htmx_request,
    log_htmx_response,
    observe_htmx,
    render_debug_panel,
    track_error,
    track_htmx_request,
    track_render_time,
)
from lexigram.admin.ui.organisms.command_palette import CommandPalette
from lexigram.admin.ui.organisms.data_table import DataTable
from lexigram.admin.ui.organisms.dynamic_form import DynamicForm
from lexigram.admin.ui.organisms.pagination import Pagination
from lexigram.admin.ui.organisms.sidebar import Sidebar, SidebarItem, SidebarSection
from lexigram.admin.ui.organisms.task_progress import TaskProgress
from lexigram.admin.ui.organisms.topbar import ThemeToggle, TopBar
from lexigram.admin.ui.organisms.userbox import UserBox
from lexigram.admin.ui.state import TableState
from lexigram.admin.ui.templates.shell import AdminShell

# Public-API imports — never reach into lexigram.ui internals.
# If a symbol is missing from `lexigram.ui`, fix `lexigram-ui/src/lexigram/ui/__init__.py`
# rather than deep-path-importing here.
from lexigram.ui import (
    # Organisms
    ActivityFeed,
    # Molecules
    Alert,
    # Accessibility
    AriaAttrs,
    AriaLive,
    AriaRole,
    # Atoms — layout
    Aside,
    # Atoms — primitives
    Badge,
    # Atoms — inputs
    BelongsTo,
    Breadcrumbs,
    Button,
    Card,
    Checkbox,
    CheckboxList,
    Col,
    ColorPicker,
    # Core
    Component,
    Container,
    DateInput,
    # Config
    DebounceConfig,
    Divider,
    Dropdown,
    EmptyState,
    # Errors
    ErrorCategory,
    ErrorResponse,
    ErrorState,
    FieldError,
    Fieldset,
    FileUpload,
    Form,
    FormActions,
    Grid,
    Hidden,
    Icon,
    InputGroup,
    Label,
    Link,
    LoadingOverlay,
    MarkdownEditor,
    MetricCard,
    # Observability
    MetricProtocol,
    MetricsCollector,
    MetricType,
    Modal,
    MultiSelect,
    NumberInput,
    PasswordInput,
    Popover,
    ProgressBar,
    Radio,
    Rating,
    # Performance
    RenderCache,
    Repeater,
    ResponseOptimizer,
    RichEditor,
    RichSelect,
    Row,
    Section,
    Select,
    SimpleAlert,
    Skeleton,
    SkipLink,
    SlideOver,
    Slider,
    Spinner,
    Stack,
    StatCard,
    SubmitButton,
    # Zones
    SwapMode,
    Switch,
    TabPanel,
    Tabs,
    TagsInput,
    TextArea,
    TextInput,
    TimePicker,
    Toast,
    Toggle,
    Tooltip,
    Zone,
    Zones,
    add_htmx_timing_header,
    announce,
    announce_table_update,
    button_aria,
    debounced_search_attrs,
    dialog_aria,
    el,
    header_aria,
    htmx_error_response,
    infinite_scroll_trigger,
    keyboard_navigation_script,
    lazy_load_placeholder,
    measure_render_time,
    not_found_error,
    permission_error,
    render_to_string,
    row_aria,
    search_aria,
    server_error,
    table_aria,
    timeout_error,
    validation_error,
)

__all__ = [
    "ActivityFeed",
    # Templates
    "AdminShell",
    "Alert",
    "AriaAttrs",
    # Accessibility (NEW)
    "AriaLive",
    "AriaRole",
    "Aside",
    "Badge",
    "BelongsTo",
    "Breadcrumbs",
    # Atoms
    "Button",
    # Molecules
    "Card",
    "Chart",
    "Checkbox",
    "CheckboxList",
    "Col",
    "ColorPicker",
    "CommandPalette",
    # Core
    "Component",
    "Container",
    # Organisms
    "DataTable",
    "DateInput",
    "DateRangeFilter",
    "DebounceConfig",
    "Dropdown",
    "DynamicForm",
    "EmptyState",
    # Error Handling (NEW)
    "ErrorCategory",
    "ErrorResponse",
    "ErrorState",
    "FieldError",
    "Fieldset",
    "FileUpload",
    "FilterBar",
    "FilterDropdown",
    "Form",
    "FormActions",
    "Grid",
    "HTMXAttrs",
    "HTMXAttrsBuilder",
    "Hidden",
    "InputGroup",
    "JumpToPage",
    "LoadingOverlay",
    "MarkdownEditor",
    "MetricCard",
    "MetricProtocol",
    # Observability (NEW)
    "MetricType",
    "MetricsCollector",
    "Modal",
    "MultiSelect",
    "NumberInput",
    "PageSizeSelector",
    "Pagination",
    "PaginationLinks",
    "PasswordInput",
    "Popover",
    "ProgressBar",
    "Radio",
    "Rating",
    "RenderCache",
    "Repeater",
    # Performance (NEW)
    "ResponseOptimizer",
    "RichEditor",
    "RichSelect",
    "Row",
    "Section",
    "Select",
    "Sidebar",
    "SidebarItem",
    "SidebarSection",
    "SimpleAlert",
    "Skeleton",
    "SkipLink",
    "SlideOver",
    "Slider",
    "Spinner",
    "Stack",
    "StatCard",
    "SubmitButton",
    "SwapMode",
    "Switch",
    "TabPanel",
    "TableState",
    "Tabs",
    "TaskProgress",
    "TextArea",
    "TextInput",
    "ThemeToggle",
    "TimePicker",
    "Toast",
    "Toggle",
    "Tooltip",
    "TopBar",
    "UserBox",
    # Zone Architecture (NEW)
    "Zone",
    "Zones",
    "add_htmx_timing_header",
    "announce",
    "announce_table_update",
    "button_aria",
    "debounced_search_attrs",
    "dialog_aria",
    "el",
    "get_health_status",
    "header_aria",
    "htmx_error_response",
    "infinite_scroll_trigger",
    "keyboard_navigation_script",
    "lazy_load_placeholder",
    "measure_render_time",
    "not_found_error",
    "permission_error",
    "render_debug_panel",
    "render_to_string",
    "row_aria",
    "search_aria",
    "server_error",
    "table_aria",
    "timeout_error",
    "track_error",
    "track_htmx_request",
    "track_render_time",
    "validation_error",
]
