"""Multimedia generation contracts — audio, music, video, image."""

from __future__ import annotations

from lexigram.contracts.multimedia.exceptions import (
    ImageGenerationError,
    MultimediaError,
    MusicGenerationError,
    ProviderNotInstalledError,
    TTSError,
    VideoGenerationError,
)
from lexigram.contracts.multimedia.protocols import (
    ImageProvider,
    MusicProvider,
    TTSProvider,
    VideoProcessor,
    VideoProvider,
)
from lexigram.contracts.multimedia.types import (
    BurnSubtitles,
    ChangeSpeed,
    ColorFilter,
    Concat,
    Crop,
    ExtractThumbnail,
    ImageRequest,
    MediaAsset,
    MusicRequest,
    MuxAudio,
    OverlayImage,
    OverlayPosition,
    OverlayText,
    RawFilter,
    SubtitleCue,
    ToGif,
    Transcode,
    TransitionSpec,
    Trim,
    TTSRequest,
    VideoOperation,
    VideoRequest,
)

__all__ = [
    "BurnSubtitles",
    "ChangeSpeed",
    "ColorFilter",
    "Concat",
    "Crop",
    "ExtractThumbnail",
    "ImageGenerationError",
    "ImageProvider",
    "ImageRequest",
    "MediaAsset",
    "MultimediaError",
    "MusicGenerationError",
    "MusicProvider",
    "MusicRequest",
    "MuxAudio",
    "OverlayImage",
    "OverlayPosition",
    "OverlayText",
    "ProviderNotInstalledError",
    "RawFilter",
    "SubtitleCue",
    "TTSError",
    "TTSProvider",
    "TTSRequest",
    "ToGif",
    "Transcode",
    "TransitionSpec",
    "Trim",
    "VideoGenerationError",
    "VideoOperation",
    "VideoProcessor",
    "VideoProvider",
    "VideoRequest",
]
