services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "26333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  ai:
    build: .
    command: python -m lexigram_example_ai.main
    depends_on:
      - qdrant


volumes:
  qdrant_data:
