"""Provider wiring for the content generation demo.

Convention followed: **Provider pattern** — ``ContentGenProvider`` is the
canonical shape (mirrors ``lexigram-auth`` + the boot-phase ``bind()``
contract in ``lexigram.contracts.core.di``):

- ``register()`` only *declares* bindings.  Zero-arg factories cover
  purely config-derived services; dependency-full services are declared
  as class bindings and instantiated in :meth:`boot`.
- ``boot()`` resolves cross-module dependencies after every provider
  has registered and rebinds the concrete instances via
  ``container.bind()``.
- Controllers are constructed by the router from the container; ``boot``
  binds their prebuilt instances so per-request resolution reuses them.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from content_gen.config import ContentGenConfig
from content_gen.controllers.api import ContentApiController
from lexigram.contracts.core.health import (
    HealthCheckCategory,
    HealthCheckResult,
    HealthStatus,
)
from lexigram.di.provider import Provider

if TYPE_CHECKING:
    from lexigram.contracts.core.di import (
        ContainerRegistrarProtocol,
        ContainerResolverProtocol,
    )

__all__ = ["ContentGenProvider"]


class ContentGenProvider(Provider):
    """Bind the content generation services as container-managed singletons."""

    name = "content_gen"

    config_key: str | None = "content_gen"
    config_model: type | None = ContentGenConfig

    async def register(self, container: ContainerRegistrarProtocol) -> None:
        """Declare bindings; concrete wiring happens in :meth:`boot`."""
        cfg = self.config or ContentGenConfig()

        container.singleton(ContentGenConfig, instance=cfg)

        # Class bindings so the keys exist; boot() replaces them with
        # fully-wired instances via container.bind().
        container.singleton(ContentApiController, ContentApiController)

    async def boot(self, container: ContainerResolverProtocol) -> None:
        """Resolve cross-module dependencies and bind concrete instances."""
        from content_gen.repository.scripted_llm import ScriptedLLMClient
        from content_gen.services.extractor import ProductExtractor
        from content_gen.services.generator import ContentGenerator

        cfg = await container.resolve(ContentGenConfig)

        # Create the LLM client (scripted for demo/testing)
        llm_client = ScriptedLLMClient(
            responses={
                "description": "This is a professionally crafted product description generated by the content system.",
                "product": '{"name": "Wireless Mouse", "price": 29.99, "category": "Electronics", "features": ["ergonomic", "wireless"]}',
                "casual": "Hey there! This is a fun and friendly take on the topic.",
                "technical": "The system employs advanced neural networks for content synthesis.",
            }
        )

        # Create services
        generator = ContentGenerator(
            llm_client=llm_client,
            default_style=cfg.default_style,
            max_retries=cfg.max_retries,
        )
        extractor = ProductExtractor(llm_client=llm_client)

        # Bind the wired controller
        container.bind(
            ContentApiController,
            ContentApiController(generator=generator, extractor=extractor),
        )

    async def health_check(self, timeout: float = 5.0) -> HealthCheckResult:
        """Report readiness of the content generator."""
        return HealthCheckResult(
            component=self.name,
            status=HealthStatus.HEALTHY,
            category=HealthCheckCategory.READINESS,
        )
