"""Admin CSRF protection middleware."""

from __future__ import annotations

from typing import Any

from starlette.requests import Request as StarletteRequest
from starlette.types import ASGIApp, Receive, Scope, Send

from lexigram.admin.auth.protocols import AdminCsrfServiceProtocol
from lexigram.admin.auth.types import AdminSecurityEventType
from lexigram.logging import get_logger

logger = get_logger(__name__)

# Paths that bypass CSRF validation (relative to admin mount point)
_CSRF_BYPASS_PATHS: frozenset[str] = frozenset(
    {
        "/login",
        "/setup",
        "/health",
    }
)

# Methods that require CSRF validation
_CSRF_METHODS: frozenset[str] = frozenset({"POST", "PUT", "PATCH", "DELETE"})


class AdminCsrfMiddleware:
    """CSRF protection middleware for admin panel routes.

    Validates CSRF tokens on all state-mutating requests (POST/PUT/PATCH/DELETE).
    Tokens are session-scoped HMAC-SHA256 values generated by AdminCsrfService.

    Bypasses validation for:
    - GET, HEAD, OPTIONS requests (safe methods)
    - Login and setup pages (pre-session forms)
    - Static file paths
    - Health check endpoint
    """

    def __init__(
        self,
        app: ASGIApp,
        csrf_service: AdminCsrfServiceProtocol,
        audit_service: Any = None,
    ) -> None:
        """Initialize with ASGI app and CSRF service.

        Args:
            app: The next ASGI application.
            csrf_service: CSRF token validation service.
            audit_service: Optional audit service for CSRF violation events.
        """
        self._app = app
        self._csrf_service = csrf_service
        self._audit_service = audit_service

    async def _audit_violation(self, scope: Scope, reason: str) -> None:
        """Record a CSRF violation, best-effort."""
        if not self._audit_service:
            return
        try:
            client = scope.get("client")
            await self._audit_service.log_event(
                event_type=AdminSecurityEventType.CSRF_VIOLATION,
                ip_address=client[0] if client else "unknown",
                user_agent="",
                success=False,
                metadata={"path": scope.get("path", ""), "reason": reason},
            )
        except Exception:  # noqa: BLE001 — audit failures must not break requests
            logger.warning("csrf.audit_failed", reason=reason)

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        """ASGI entry point.

        Args:
            scope: ASGI scope dict.
            receive: ASGI receive callable.
            send: ASGI send callable.
        """
        if scope.get("type") != "http":
            await self._app(scope, receive, send)
            return

        method = scope.get("method", "")
        path = scope.get("path", "")

        # Skip non-mutating methods
        if method not in _CSRF_METHODS:
            await self._app(scope, receive, send)
            return

        # Skip bypass paths
        if self._is_bypass_path(path):
            await self._app(scope, receive, send)
            return

        request = StarletteRequest(scope, receive)

        if not await self._validate_csrf(request):
            await self._send_403(send)
            return

        await self._app(scope, receive, send)

    def _is_bypass_path(self, path: str) -> bool:
        """Check if the path bypasses CSRF validation.

        Args:
            path: Request path.

        Returns:
            True if CSRF validation should be skipped.
        """
        # Strip the admin prefix if present
        check_path = path
        if check_path.startswith("/admin"):
            check_path = check_path[len("/admin") :]

        if check_path in _CSRF_BYPASS_PATHS:
            return True
        return bool(check_path.startswith("/static"))

    async def _validate_csrf(self, request: StarletteRequest) -> bool:
        """Extract and validate CSRF token from request.

        Content-Type dictates token location (AUTH-07):
        - ``application/x-www-form-urlencoded`` / ``multipart/form-data``
          → token from form body.
        - Any other Content-Type (JSON, etc.) → token from ``X-CSRF-Token``
          header.
        Mismatches are rejected with 403.

        Args:
            request: Starlette Request object.

        Returns:
            True if CSRF token is valid, False otherwise.
        """
        try:
            session = getattr(request, "session", {})
            session_id: str = session.get("admin_user_id", "anonymous")

            content_type = (request.headers.get("content-type") or "").lower()
            is_form = content_type.startswith(
                ("application/x-www-form-urlencoded", "multipart/form-data")
            )

            token: str | None = None

            if is_form:
                try:
                    form = await request.form()
                    request.scope["admin_form_data"] = form
                    raw = form.get("csrf_token")
                    if isinstance(raw, str):
                        token = raw
                except (RuntimeError, ValueError, OSError):  # noqa: BLE001
                    pass
                # Fall back to X-CSRF-Token header (HTMX injects this via
                # htmx:configRequest). Needed when hx-include triggers
                # form-encoding but the token lives in the header.
                if not token:
                    token = request.headers.get("X-CSRF-Token")
            else:
                # JSON, fetch, etc.: token must come from X-CSRF-Token header
                token = request.headers.get("X-CSRF-Token")

            if not token:
                logger.warning(
                    "csrf.token_missing",
                    path=str(request.url.path),
                    content_type=content_type,
                )
                await self._audit_violation(request.scope, "token_missing")
                return False

            is_valid = self._csrf_service.validate_token(session_id, token)
            if not is_valid:
                logger.warning(
                    "csrf.token_invalid",
                    path=str(request.url.path),
                    session_id=session_id,
                )
                await self._audit_violation(request.scope, "token_invalid")
            return is_valid
        except Exception:  # noqa: BLE001
            logger.warning("csrf.validation_error")
            return False

    async def _send_403(self, send: Send) -> None:
        """Send a 403 Forbidden HTML response.

        Args:
            send: ASGI send callable.
        """
        body = (
            b"<!DOCTYPE html>\n"
            b"<html><head><title>403 Forbidden</title></head>\n"
            b"<body><h1>403 Forbidden</h1>\n"
            b"<p>Invalid or missing CSRF token. "
            b"Please reload the page and try again.</p>\n"
            b'<a href="/admin/">Return to Admin</a>\n'
            b"</body></html>"
        )
        await send(
            {
                "type": "http.response.start",
                "status": 403,
                "headers": [
                    [b"content-type", b"text/html; charset=utf-8"],
                    [b"content-length", str(len(body)).encode()],
                ],
            }
        )
        await send(
            {
                "type": "http.response.body",
                "body": body,
            }
        )


__all__ = ["AdminCsrfMiddleware"]
