"""Oridecon — Async-first DI application framework for Python.

This package exposes a curated root API while avoiding import-time circular
imports via lazy attribute loading.
"""

from __future__ import annotations

import importlib
import importlib.metadata
import pkgutil
from typing import Any, Final

# Critical: enable namespace-package discovery for oridecon-* distributions.
__path__ = pkgutil.extend_path(__path__, __name__)

from oridecon.constants import __version__

_ExportSpec = tuple[str, str | None]
_EXPORTS: Final[dict[str, _ExportSpec]] = {
    "AbstractBuilder": ("oridecon.primitives.builder", "AbstractBuilder"),
    "ActionHandler": ("oridecon.types", "ActionHandler"),
    "AppState": ("oridecon.app.base", "AppState"),
    "Application": ("oridecon.app.base", "Application"),
    "AsyncServiceFactory": ("oridecon.types", "AsyncServiceFactory"),
    "BaseConfig": ("oridecon.config", "BaseConfig"),
    "CacheBackendProtocol": ("oridecon.contracts.infra.cache", "CacheBackendProtocol"),
    "ClockProtocol": ("oridecon.contracts.core.clock", "ClockProtocol"),
    "clock": ("oridecon.primitives.clock", None),
    "ConfigProtocol": ("oridecon.contracts.core.config", "ConfigProtocol"),
    "ConfigProvider": ("oridecon.config.di.provider", "ConfigProvider"),
    "ConfigurationError": ("oridecon.exceptions", "ConfigurationError"),
    "Container": ("oridecon.di.container", "Container"),
    "ContainerBuilder": ("oridecon.di.builder", "ContainerBuilder"),
    "ContainerError": ("oridecon.contracts.exceptions.container", "ContainerError"),
    "Context": ("oridecon.primitives.context", "Context"),
    "ContextKey": ("oridecon.primitives.context", "ContextKey"),
    "CoreInfrastructureProvider": (
        "oridecon.primitives.di.provider",
        "CoreInfrastructureProvider",
    ),
    "CoreModule": ("oridecon.app.module", "CoreModule"),
    "CoreProvider": ("oridecon.app.di.provider", "CoreProvider"),
    "DomainModelError": ("oridecon.exceptions", "DomainModelError"),
    "DomainError": ("oridecon.contracts.exceptions.domain", "DomainError"),
    "DynamicModule": ("oridecon.di.module", "DynamicModule"),
    "Err": ("oridecon.result", "Err"),
    "ErrorHandler": ("oridecon.types", "ErrorHandler"),
    "FilterHandler": ("oridecon.types", "FilterHandler"),
    "EventMiddlewareProtocol": ("oridecon.contracts.events", "EventMiddlewareProtocol"),
    "EventStream": ("oridecon.reactive.core", "EventStream"),
    "GuardFunction": ("oridecon.types", "GuardFunction"),
    "hashing": ("oridecon.security.hashing.ambient", None),
    "HookPriority": ("oridecon.hooks", "HookPriority"),
    "HookRegistry": ("oridecon.hooks", "HookRegistry"),
    "HookRegistryProtocol": ("oridecon.hooks", "HookRegistryProtocol"),
    "identity": ("oridecon.identity.ambient", None),
    "Injectable": ("oridecon.di.decorators", "Injectable"),
    "InjectionError": ("oridecon.exceptions", "InjectionError"),
    "IdGeneratorProtocol": ("oridecon.contracts.core.identity", "IdGeneratorProtocol"),
    "IdentityProvider": ("oridecon.identity.di.provider", "IdentityProvider"),
    "InfrastructureError": (
        "oridecon.contracts.exceptions.infra",
        "InfrastructureError",
    ),
    "Invoker": ("oridecon.app.invoker", "Invoker"),
    "OrideconConfig": ("oridecon.config", "OrideconConfig"),
    "OrideconError": ("oridecon.contracts.exceptions", "OrideconError"),
    "OrideconException": ("oridecon.exceptions", "OrideconException"),
    "LoggingConfig": ("oridecon.config", "LoggingConfig"),
    "LoggingProvider": ("oridecon.logging.di.provider", "LoggingProvider"),
    "LoggerFactoryProtocol": (
        "oridecon.contracts.core.logging",
        "LoggerFactoryProtocol",
    ),
    "LoggerProtocol": ("oridecon.contracts.core.logging", "LoggerProtocol"),
    "RedactorProtocol": ("oridecon.contracts.core.logging", "RedactorProtocol"),
    "MiddlewareChain": ("oridecon.middleware.core.chain", "MiddlewareChain"),
    "MiddlewareConfig": ("oridecon.middleware.config", "MiddlewareConfig"),
    "MiddlewareFactory": ("oridecon.types", "MiddlewareFactory"),
    "MiddlewareModule": ("oridecon.middleware.module", "MiddlewareModule"),
    "MiddlewareProvider": ("oridecon.middleware.di.provider", "MiddlewareProvider"),
    "MiddlewareRegistry": ("oridecon.middleware.core.registry", "MiddlewareRegistry"),
    "Module": ("oridecon.di.module", "Module"),
    "ModuleBase": ("oridecon.di.module", "ModuleBase"),
    "ModuleError": ("oridecon.di.module", "ModuleError"),
    "Ok": ("oridecon.result", "Ok"),
    "ops": ("oridecon.reactive", "ops"),
    "NotFoundError": ("oridecon.contracts.exceptions.domain", "NotFoundError"),
    "PluginEngineProvider": ("oridecon.plugins.engine", "PluginEngineProvider"),
    "PluginsModule": ("oridecon.plugins.module", "PluginsModule"),
    "PluginStateError": ("oridecon.plugins.exceptions", "PluginStateError"),
    "Provider": ("oridecon.di.provider", "Provider"),
    "ProviderError": ("oridecon.contracts.exceptions.provider", "ProviderError"),
    "ProviderPriority": ("oridecon.contracts.core.provider", "ProviderPriority"),
    "ProviderState": ("oridecon.di.provider", "ProviderState"),
    "Registry": ("oridecon.primitives.registry", "Registry"),
    "RequestContext": ("oridecon.primitives.context", "RequestContext"),
    "Result": ("oridecon.result", "Result"),
    "ResultHandler": ("oridecon.types", "ResultHandler"),
    "ResultPipeline": ("oridecon.result", "ResultPipeline"),
    "RetryOptions": ("oridecon.reactive.retry", "RetryOptions"),
    "retry": ("oridecon.reactive.retry", "retry"),
    "SamplingConfig": ("oridecon.config", "SamplingConfig"),
    "Scope": ("oridecon.di.container", "Scope"),
    "SerializationError": ("oridecon.exceptions", "SerializationError"),
    "Stream": ("oridecon.reactive.core", "Stream"),
    "Subject": ("oridecon.reactive.subjects", "Subject"),
    "SystemClock": ("oridecon.primitives.clock", "current"),
    "share": ("oridecon.reactive.subjects", "share"),
    "as_result": ("oridecon.result", "as_result"),
    "as_result_sync": ("oridecon.result", "as_result_sync"),
    "buildable": ("oridecon.primitives.builder", "buildable"),
    "builder_field": ("oridecon.primitives.builder", "builder_field"),
    "collect": ("oridecon.result", "collect"),
    "configure_logging": ("oridecon.logging", "configure_logging"),
    "create_app": ("oridecon.app.factory", "create_app"),
    "create_module": ("oridecon.di.module", "create_module"),
    "discover_plugins": ("oridecon.plugins.discovery", "discover_plugins"),
    "discover_providers": ("oridecon.plugins.discovery", "discover_providers"),
    "get_logger": ("oridecon.logging", "get_logger"),
    "inject": ("oridecon.di.decorators", "inject"),
    "injectable": ("oridecon.di.decorators", "injectable"),
    "load_disabled": ("oridecon.plugins.state", "load_disabled"),
    "module": ("oridecon.di.module", "module"),
    "partition": ("oridecon.result", "partition"),
    "provide": ("oridecon.di.function_provider", "provide"),
    "request_context": ("oridecon.primitives.context", "request_scope"),
    "run_application": ("oridecon.app.runner", "run_application"),
    "save_disabled": ("oridecon.plugins.state", "save_disabled"),
    "scoped": ("oridecon.di.decorators", "scoped"),
    "singleton": ("oridecon.di.decorators", "singleton"),
    "transient": ("oridecon.di.decorators", "transient"),
    "try_catch": ("oridecon.result", "try_catch"),
    "update_disabled": ("oridecon.plugins.state", "update_disabled"),
}


def __getattr__(name: str) -> Any:
    """Lazy-load exports to avoid circular imports during package init."""
    try:
        module_path, attr_name = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module 'oridecon' has no attribute {name!r}") from exc

    if attr_name is None:
        module = importlib.import_module(module_path)
        globals()[name] = module
        return module

    module = importlib.import_module(module_path)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return eager and lazy exports for introspection tools."""
    return sorted(set(globals()) | set(_EXPORTS) | {"__version__"})


__all__ = [
    "AbstractBuilder",
    "ActionHandler",
    "AppState",
    "Application",
    "AsyncServiceFactory",
    "BaseConfig",
    "CacheBackendProtocol",
    "ClockProtocol",
    "ClockProvider",
    "ConfigProtocol",
    "ConfigProvider",
    "ConfigurationError",
    "Container",
    "ContainerBuilder",
    "ContainerError",
    "Context",
    "ContextKey",
    "CoreInfrastructureProvider",
    "CoreModule",
    "CoreProvider",
    "DomainError",
    "DomainModelError",
    "DynamicModule",
    "Err",
    "ErrorHandler",
    "EventMiddlewareProtocol",
    "EventStream",
    "FilterHandler",
    "GuardFunction",
    "HookPriority",
    "HookRegistry",
    "HookRegistryProtocol",
    "IdGeneratorProtocol",
    "IdentityProvider",
    "InfrastructureError",
    "Injectable",
    "InjectionError",
    "Invoker",
    "OrideconConfig",
    "OrideconError",
    "OrideconException",
    "LoggerFactoryProtocol",
    "LoggerProtocol",
    "LoggingConfig",
    "LoggingProvider",
    "MiddlewareChain",
    "MiddlewareConfig",
    "MiddlewareFactory",
    "MiddlewareModule",
    "MiddlewareProvider",
    "MiddlewareRegistry",
    "Module",
    "ModuleBase",
    "ModuleError",
    "NotFoundError",
    "Ok",
    "PluginEngineProvider",
    "PluginStateError",
    "PluginsModule",
    "Provider",
    "ProviderError",
    "ProviderPriority",
    "ProviderState",
    "RedactorProtocol",
    "Registry",
    "RequestContext",
    "Result",
    "ResultHandler",
    "ResultPipeline",
    "RetryOptions",
    "SamplingConfig",
    "Scope",
    "SerializationError",
    "Stream",
    "Subject",
    "SystemClock",
    "__version__",
    "as_result",
    "as_result_sync",
    "buildable",
    "builder_field",
    "clock",
    "collect",
    "configure_logging",
    "create_app",
    "create_module",
    "discover_plugins",
    "discover_providers",
    "get_logger",
    "hashing",
    "identity",
    "inject",
    "injectable",
    "load_disabled",
    "module",
    "ops",
    "partition",
    "provide",
    "request_context",
    "retry",
    "run_application",
    "save_disabled",
    "scoped",
    "share",
    "singleton",
    "transient",
    "try_catch",
    "try_catch_sync",
    "update_disabled",
]
