"""Recon-pinned framework facts for the builder package.

Verified 2026-08-25/26 against source (see .superpowers builder spec):

- ``DatabaseModule.configure(config=<url|DatabaseConfig>)`` — no url=/dialect=.
- Controllers return ``Ok/Err``; result bridge maps to ProblemDetail.
- SSE via ``lexigram.web.sse.EventSourceResponse``.
- Entities in generated apps: Pydantic + ``GenericRepository`` over
  ``DatabaseProviderProtocol``; dual-URL sqlite rule (runtime
  ``sqlite:///``, migrations ``sqlite+aiosqlite:///``).
"""

from __future__ import annotations

from importlib import metadata

__version__: str
try:
    __version__ = metadata.version("lexigram-builder")
except Exception:  # noqa: BLE001 - metadata unavailable in raw checkouts
    __version__ = "0.0.0"

BUILDER_DEFAULT_HOST = "127.0.0.1"
BUILDER_DEFAULT_PORT = 7200

ENV_BUILDER_PORT = "LEX_BUILDER_PORT"
ENV_BUILDER_HOST = "LEX_BUILDER_HOST"
ENV_PROJECTS_DIR = "LEX_BUILDER_PROJECTS_DIR"

PREVIEW_PORT_RANGE_START = 8100
PREVIEW_PORT_RANGE_END = 8199
PREVIEW_HEALTH_TIMEOUT_SECONDS = 15.0

GRAPH_SCHEMA_VERSION = 1

GENERATED_HEADER = "# generated by lexigram-builder - do not edit"
