[project]
name = "{{ project_name }}"
version = "0.1.2"
description = "Web API service built with Lexigram"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lexigram",
    "lexigram-web",
    "lexigram-sql",
    "uvicorn",
]

[tool.hatch.build.targets.wheel]
packages = ["src/{{ package_name }}"]
