"""Generator output gate.

Renders every generator registered through ``lexigram.cli.contributors``
entry points and verifies that each produced file parses and imports
against the real lexigram APIs.  This keeps the generator SDK honest:
any template drift (invalid syntax, missing/renamed framework symbols)
fails the gate instead of shipping broken scaffolds.

App-local imports are expected and reported separately, not treated as
failures:

- ``from repositories...`` — sibling package generated by
  ``lexigram gen repository`` (controller/resource scaffolds)
- ``from app...`` — the CLI test generator's configurable application
  package (``package_name`` option, defaults to ``app``)

Run:

    python dev/checks/generator_output.py

Requires the development environment (``uv run python ...``) where the
lexigram packages are importable.
"""

from __future__ import annotations

import ast
import importlib
import inspect
from pathlib import Path
import sys
import tempfile
import tomllib
import types

ROOT = Path(__file__).resolve().parent.parent.parent

PLACEHOLDER_PREFIXES = ("app", "repositories")


def iter_pyprojects() -> list[Path]:
    """Yield every pyproject.toml owning a CLI contributor."""
    seen: set[Path] = set()
    for pattern in (
        "packages/*/pyproject.toml",
        "experimental/apps/*/pyproject.toml",
        "experimental/ai/*/pyproject.toml",
        "core/*/pyproject.toml",
    ):
        for path in ROOT.glob(pattern):
            path = path.resolve()
            if path not in seen:
                seen.add(path)
                yield path


def collect_definitions() -> dict[str, tuple[str, str]]:
    """Map generator name -> (generator_path, pyproject dir name)."""
    definitions: dict[str, tuple[str, str]] = {}
    for pyproject in iter_pyprojects():
        try:
            data = tomllib.loads(pyproject.read_text())
        except Exception:
            continue
        entries = (
            data.get("project", {})
            .get("entry-points", {})
            .get("lexigram.cli.contributors", {})
        )
        for entry in entries.values():
            module_path, _, attr = entry.partition(":")
            try:
                module = importlib.import_module(module_path)
            except Exception as exc:  # noqa: BLE001
                print(f"[warn] cannot import contributor {module_path}: {exc}")
                continue
            contributor = getattr(module, attr)() if attr else module
            try:
                generator_defs = contributor.get_generators()
            except Exception as exc:  # noqa: BLE001
                print(f"[warn] cannot enumerate {entry}: {exc}")
                continue
            for definition in generator_defs:
                definitions[definition.name] = (
                    definition.generator_path,
                    pyproject.parent.name,
                )
    return definitions


def callable_options(function) -> dict:
    """Pick generous sample options for a generate() signature."""
    signature = inspect.signature(function)
    options: dict = {}
    skipped = {"name", "self", "output_dir", "dry_run", "force", "doc", "options"}
    for name, parameter in signature.parameters.items():
        if name in skipped:
            continue
        if parameter.kind in (
            inspect.Parameter.VAR_KEYWORD,
            inspect.Parameter.VAR_POSITIONAL,
        ):
            continue
        if parameter.default is not inspect.Parameter.empty:
            options[name] = parameter.default
    if "fields_str" in signature.parameters:
        options["fields_str"] = "email:str,age:int?"
    if "exception_type" in signature.parameters:
        options["exception_type"] = "ValueError"
    if "key_type" in signature.parameters:
        options["key_type"] = "str"
    if "critical" in signature.parameters:
        options["critical"] = False
    if "path" in signature.parameters:
        options["path"] = "/health"
    if "test_type" in signature.parameters:
        options["test_type"] = "model"
    if "package_name" in signature.parameters:
        options["package_name"] = "app"
    if "backend" in signature.parameters:
        options["backend"] = "meilisearch"
    if "test_type" in signature.parameters:
        options["test_type"] = "model"
    return options


def is_app_local_import(error: ModuleNotFoundError) -> bool:
    """True for the intentional app-local placeholder imports."""
    name = error.name or ""
    return any(
        name == prefix or name.startswith(f"{prefix}.")
        for prefix in PLACEHOLDER_PREFIXES
    )


def validate_file(path: Path) -> tuple[bool, str]:
    """Parse and import a single generated file."""
    source = path.read_text()
    try:
        ast.parse(source)
    except SyntaxError as exc:
        return False, f"SyntaxError: {exc}"

    module = types.ModuleType(path.stem)
    module.__file__ = str(path)
    sys.modules[path.stem] = module
    try:
        exec(compile(source, str(path), "exec"), module.__dict__)  # noqa: S102
        return True, "OK"
    except ModuleNotFoundError as exc:
        if is_app_local_import(exc):
            return True, f"PLACEHOLDER ({exc.name})"
        return False, f"ModuleNotFoundError: {exc.name}"
    except Exception as exc:  # noqa: BLE001
        return False, f"{type(exc).__name__}: {exc}"
    finally:
        sys.modules.pop(path.stem, None)


def main() -> int:
    """Run the gate and return the process exit code."""
    definitions = collect_definitions()
    print(f"Rendering {len(definitions)} registered generators ...")

    failures: list[tuple[str, str, str]] = []
    placeholders: list[tuple[str, str, str]] = []
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        for name in sorted(definitions):
            generator_path, _ = definitions[name]
            module_path, _, cls_name = generator_path.partition(":")
            try:
                cls = getattr(importlib.import_module(module_path), cls_name)
                generator = cls(output_dir=root / name)
            except Exception as exc:  # noqa: BLE001
                failures.append(
                    (name, generator_path, f"construct: {type(exc).__name__}: {exc}")
                )
                continue
            try:
                result = generator.generate(
                    "demo",
                    output_dir=root / name,
                    **callable_options(generator.generate),
                )  # type: ignore[attr-defined]
            except Exception as exc:  # noqa: BLE001
                failures.append(
                    (name, generator_path, f"generate: {type(exc).__name__}: {exc}")
                )
                continue
            created = [Path(p) for p in result.files_created if Path(p).exists()]
            if not created:
                created = [p for p in (root / name).rglob("*") if p.is_file()]
            if not created:
                failures.append((name, generator_path, "no output files"))
                continue
            for path in sorted(set(created)):
                ok, message = validate_file(path)
                if ok and message.startswith("PLACEHOLDER"):
                    placeholders.append((name, path.name, message))
                elif not ok:
                    failures.append((name, path.relative_to(root).as_posix(), message))

    print(
        f"OK: {len(definitions) - len(failures)}  Placeholders: {len(placeholders)}  Failures: {len(failures)}"
    )
    for name, path, message in placeholders:
        print(f"  [placeholder] {name}/{path}: {message}")
    for name, path, message in failures:
        print(f"  [FAIL] {name}/{path}: {message}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
