"""Seeded offline fixtures for the content generation demo.

These are plain data structures — no framework imports, no I/O.
They represent the scripted responses that the LLM client returns:

- ``SCRIPTED_RESPONSES`` — keyword → response mappings for deterministic testing

In a real application these would come from a real LLM client.
For the demo, scripted responses keep the focus on provider wiring
rather than LLM API calls.
"""

from __future__ import annotations

SCRIPTED_RESPONSES: dict[str, str] = {
    "description": "This is a professionally crafted product description generated by the content system.",
    "product": '{"name": "Wireless Mouse", "price": 29.99, "category": "Electronics", "features": ["ergonomic", "wireless"]}',
    "casual": "Hey there! This is a fun and friendly take on the topic.",
    "technical": "The system employs advanced neural networks for content synthesis.",
}
