services:
  dev:
    image: mcr.microsoft.com/devcontainers/python:3.11
    environment:
      ORI_DB__URL: postgresql://oridecon:oridecon@postgres:5432/oridecon
      ORI_CACHE__REDIS__URL: redis://redis:6379/0
    volumes:
      - ..:/workspaces/oridecon-dev
    command: sleep infinity