"""In-memory relay job registry for job-based media generation.

Maps a gateway-issued job handle (a UUID generated at insertion) to a
``RelayJobRecord`` describing which channel owns the upstream job and
what the upstream's own job id is.  Records are evicted lazily on
lookup once older than the configured ``job_ttl_seconds``; an expired
or unknown handle returns ``None`` so callers can treat both as the
same not-found outcome.

Note:
    The registry is in-memory only: a gateway process restart loses
    all in-flight job mappings, and a caller polling a lost job
    receives the same not-found outcome as an unknown id.  A durable
    job store is an explicit v1 non-goal (see the async job-relay
    plan).
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
import time

from lexigram.identity.ambient import new_uuid

__all__ = ["RelayJobRecord", "RelayJobRegistry"]


@dataclass(frozen=True, slots=True)
class RelayJobRecord:
    """One in-flight relayed job's channel-affinity mapping.

    Attributes:
        channel_name: Name of the channel that owns the upstream job.
            Every poll for this job routes to this same channel.
        upstream_job_id: The job id issued by the upstream provider;
            never exposed to the caller.
        endpoint_kind: The endpoint kind the job was submitted through
            (e.g. ``"video_generation"``).
        submitted_by: Tenant id of the caller that submitted the job;
            the status poller compares it against the polling caller.
        created_at: Monotonic timestamp of the record; the registry
            evicts records older than the configured TTL.
    """

    channel_name: str
    upstream_job_id: str
    endpoint_kind: str
    submitted_by: str
    created_at: float


class RelayJobRegistry:
    """Maps gateway job ids to relay job records with TTL eviction.

    The gateway job id is generated by this registry at ``put`` time —
    callers never choose it — so a caller-visible handle can never
    collide with an upstream-issued job id.

    Attributes:
        _job_ttl_seconds: Age after which a record is evicted on the
            next lookup.
        _clock: Monotonic clock used for eviction decisions; tests
            inject a fake.
        _records: Gateway job id to record mapping.
    """

    def __init__(
        self,
        job_ttl_seconds: int,
        *,
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        """Bind the registry to a TTL and clock.

        Args:
            job_ttl_seconds: Age in seconds after which a record is
                evicted on the next ``get``.  The configuration layer
                validates this is positive.
            clock: Callable returning the current monotonic time.
                Defaults to ``time.monotonic``; tests inject a fake.
        """
        self._job_ttl_seconds = job_ttl_seconds
        self._clock = clock
        self._records: dict[str, RelayJobRecord] = {}

    def put(self, record: RelayJobRecord) -> str:
        """Store *record* under a fresh gateway-issued job id.

        Args:
            record: The channel-affinity record to store.

        Returns:
            The gateway job id the caller can hand back to consumers
            for status polling.
        """
        gateway_job_id = new_uuid()
        self._records[gateway_job_id] = record
        return gateway_job_id

    def get(self, gateway_job_id: str) -> RelayJobRecord | None:
        """Return the record for *gateway_job_id*, evicting when stale.

        An expired record is removed from storage (not merely hidden)
        so memory does not grow unbounded across many expired lookups.

        Args:
            gateway_job_id: The gateway-issued job id from ``put``.

        Returns:
            The stored record when it exists and is not older than
            ``job_ttl_seconds``, otherwise ``None`` (both unknown and
            expired ids behave identically).
        """
        record = self._records.get(gateway_job_id)
        if record is None:
            return None
        if self._clock() - record.created_at > self._job_ttl_seconds:
            del self._records[gateway_job_id]
            return None
        return record
