"""Tests for CSRFConfig defaults and CSRF middleware wiring in WebProvider."""

from __future__ import annotations

import pytest

from lexigram.web.security.config import CSRFConfig, SecurityConfig
from lexigram.web.security.csrf.protection import CSRFProtection


class TestCsrfConfig:
    """Verify CSRFConfig field defaults and presence on SecurityConfig.

    CSRFConfig is the canonical class from lexigram.web.security.
    Web security defaults apply (enabled=False, samesite="Lax").
    Web-appropriate defaults (enabled=True, excluded_paths) are set in
    WebConfig.security's default_factory rather than on the class itself.
    """

    def test_csrf_config_defaults(self) -> None:
        """CSRFConfig has excluded_paths support and sensible defaults."""
        cfg = CSRFConfig()
        assert isinstance(cfg.excluded_paths, list)
        assert cfg.cookie_secure is True
        assert cfg.cookie_name == "csrf_token"
        assert cfg.header_name == "X-CSRF-Token"

    def test_webconfigcors_security_has_csrf_enabled_by_default(self) -> None:
        """WebConfig().security.csrf is enabled by default for web's secure-by-default UX."""
        from lexigram.web.config import WebConfig

        web_cfg = WebConfig()
        assert web_cfg.security.csrf.enabled is True
        assert len(web_cfg.security.csrf.excluded_paths) > 0

    def test_web_security_config_has_csrf_field(self) -> None:
        """SecurityConfig must expose a `csrf` attribute of type CSRFConfig."""
        sec = SecurityConfig()
        assert hasattr(sec, "csrf")
        assert isinstance(sec.csrf, CSRFConfig)

    def test_csrf_config_can_be_enabled(self) -> None:
        """CSRFConfig.enabled can be set to True."""
        cfg = CSRFConfig(enabled=True)
        assert cfg.enabled is True

    def test_csrf_config_samesite_configurable(self) -> None:
        """cookie_samesite can be overridden."""
        cfg = CSRFConfig(cookie_samesite="strict")
        assert cfg.cookie_samesite == "strict"

    def test_csrf_config_excluded_paths_configurable(self) -> None:
        """excluded_paths can be replaced with a custom list."""
        cfg = CSRFConfig(excluded_paths=["/public/"])
        assert cfg.excluded_paths == ["/public/"]


class TestCsrfMiddlewareWiring:
    """Integration: CSRFProtectionMiddleware is wired when csrf.enabled = True."""

    @pytest.mark.asyncio
    async def test_csrf_middleware_present_by_default(self, test_bed) -> None:
        """CSRFProtectionMiddleware IS added by default because csrf.enabled = True (secure-by-default)."""
        from unittest.mock import MagicMock

        from lexigram.web.di.provider import WebProvider
        from lexigram.web.security.csrf.middleware import CSRFProtectionMiddleware

        web = await test_bed.resolve(WebProvider)

        added_middleware: list[type] = []

        def capture_add_middleware(cls: type, **_kwargs: object) -> None:
            added_middleware.append(cls)

        fake_app = MagicMock()
        fake_app.add_middleware = capture_add_middleware
        fake_container = MagicMock()

        await web._setup_middleware(fake_app, fake_container)

        # csrf.enabled defaults to True (secure-by-default) → CSRFProtectionMiddleware MUST be added
        assert CSRFProtectionMiddleware in added_middleware


class TestCsrfProtection:
    """Unit tests for CSRFProtection token generation and validation."""

    def _config(self) -> CSRFConfig:
        return CSRFConfig(enabled=True, _secret_key="test-secret-key-32bytes-long!!")

    def test_generate_token_returns_hex_string(self) -> None:
        """generate_token returns a non-empty hex string."""
        csrf = CSRFProtection(config=self._config())
        token = csrf.generate_token(session_id="user-123")
        assert isinstance(token, str)
        assert len(token) > 0
        # Must be valid hex
        int(token, 16)

    def test_generate_token_raises_without_secret_key(self) -> None:
        """generate_token raises ValueError when secret_key is not configured."""
        csrf = CSRFProtection(config=CSRFConfig(enabled=True))
        with pytest.raises(ValueError, match="secret_key must be set"):
            csrf.generate_token(session_id="user-123")

    def test_validate_token_accepts_valid_token(self) -> None:
        """validate_token returns True for a token generated by generate_token."""
        csrf = CSRFProtection(config=self._config())
        token = csrf.generate_token(session_id="user-123")
        assert csrf.validate_token(token, session_id="user-123") is True

    def test_validate_token_rejects_wrong_session(self) -> None:
        """validate_token returns False when the session_id doesn't match."""
        csrf = CSRFProtection(config=self._config())
        token = csrf.generate_token(session_id="user-123")
        assert csrf.validate_token(token, session_id="other-user") is False

    def test_validate_token_rejects_empty_inputs(self) -> None:
        """validate_token returns False for empty token or session_id."""
        csrf = CSRFProtection(config=self._config())
        assert csrf.validate_token("", session_id="user-123") is False
        assert csrf.validate_token("sometoken", session_id="") is False

    def test_validate_token_rejects_malformed_token(self) -> None:
        """validate_token returns False for a token with wrong length."""
        csrf = CSRFProtection(config=self._config())
        assert csrf.validate_token("tooshort", session_id="user-123") is False

    def test_validate_token_raises_without_secret_key(self) -> None:
        """validate_token raises ValueError when secret_key is not configured."""
        csrf = CSRFProtection(config=CSRFConfig(enabled=True))
        with pytest.raises(ValueError, match="secret_key must be set"):
            csrf.validate_token("sometoken", session_id="user-123")

    def test_config_property(self) -> None:
        """config property returns the CSRFConfig passed at construction."""
        config = self._config()
        csrf = CSRFProtection(config=config)
        assert csrf.config is config


class TestCsrfMiddlewareWiringEnabled:
    """Integration: CSRFProtectionMiddleware is wired when csrf.enabled = True."""

    @pytest.mark.asyncio
    async def test_csrf_middleware_present_when_enabled(self, test_bed) -> None:
        """When csrf.enabled = True, CSRFProtectionMiddleware is added to the stack."""
        from unittest.mock import MagicMock

        from lexigram.web.di.provider import WebProvider
        from lexigram.web.security.config import CSRFConfig
        from lexigram.web.security.csrf.middleware import CSRFProtectionMiddleware

        web = await test_bed.resolve(WebProvider)

        # Patch the security config to enable CSRF
        web.web_config.security.csrf = CSRFConfig(
            enabled=True,
            cookie_samesite="strict",
            cookie_secure=False,
            excluded_paths=["/health"],
        )

        added_middleware: list[type] = []

        def capture_add_middleware(cls: type, **_kwargs: object) -> None:
            added_middleware.append(cls)

        fake_app = MagicMock()
        fake_app.add_middleware = capture_add_middleware
        fake_container = MagicMock()

        await web._setup_middleware(fake_app, fake_container)

        assert CSRFProtectionMiddleware in added_middleware
