"""Graph document domain models (frozen, source-of-truth canvas state)."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Position:
    """Canvas coordinates."""

    x: float
    y: float


# Global capability flags toggled from the Project Settings screen. These are
# app-wide switches; per-entity detail lives on canvas nodes / dedicated
# screens (see docs/NODE_VS_SCREEN.md).
APP_FEATURE_KEYS: tuple[str, ...] = (
    "enableAuth", "enableAdmin", "enableApiDocs", "enableWebsockets",
    "enableBackgroundJobs", "enableSearch", "enableFileUpload",
    "enableAuditLog", "enableRateLimiting", "enableCaching",
    "enableEmail", "enableSse",
)


@dataclass(frozen=True, slots=True)
class AppSettingsConfig:
    """Single per-graph application settings node."""

    app_name: str
    port: int
    db: str
    structure: str = "minimal"
    # Set of enabled capability keys (subset of APP_FEATURE_KEYS).
    features: frozenset[str] = frozenset()


@dataclass(frozen=True, slots=True)
class FieldConfig:
    """One entity field."""

    name: str
    type: str
    nullable: bool = False


@dataclass(frozen=True, slots=True)
class EntityConfig:
    """An entity node: snake_case name plus one or more fields.

    ``seed_data`` is JSON-encoded row dicts authored in the Seed Data
    screen; a wired seeder emits them as ``SEED_DATA``. Empty means the
    framework generator's sample row is kept.
    """

    name: str
    fields: tuple[FieldConfig, ...]
    seed_data: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class RouteConfig:
    """A route node bound to an entity via an edge."""

    ops: tuple[str, ...]
    path_prefix: str | None = None


@dataclass(frozen=True, slots=True)
class MiddlewareConfig:
    """A middleware node: a named request/response pipeline component.

    Attributes:
        name: snake_case identifier (file/class stem).
        type: Middleware kind (cors, logging, compression, custom, …).
        order: Stack order hint (lower runs earlier).
    """

    name: str
    type: str = "custom"
    order: int = 100


@dataclass(frozen=True, slots=True)
class CronConfig:
    """A cron node: a background task triggered on a schedule.

    Maps to the framework's lexigram-tasks ``@scheduled`` decorator.

    Attributes:
        name: snake_case task identifier (module/function stem).
        schedule: Cron expression (5 fields).
        enabled: When False the task is generated but left unregistered.
        description: Human-readable docstring for the generated task.
    """

    name: str
    schedule: str = "0 * * * *"
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class WebhookConfig:
    """A webhook node: an inbound HTTP trigger endpoint.

    Maps to the framework ``webhook`` generator (payload + HMAC verification)
    wrapped by a thin framework ``Controller`` that mounts a ``POST`` route.

    Attributes:
        name: snake_case identifier (module/path stem).
        path: HTTP path the endpoint is mounted at (e.g. ``/webhooks/payment``).
        verify_signature: When True the handler verifies an HMAC signature
            using a server-side secret read from the environment.
        secret_env: Environment variable holding the shared HMAC secret.
        description: Human-readable docstring for the generated webhook.
        enabled: When False the webhook is generated but not registered.
    """

    name: str
    path: str = ""
    verify_signature: bool = True
    secret_env: str = ""
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class JobConfig:
    """A job node: a background ``@task`` action enqueued by a trigger.

    Unlike a cron node (which schedules itself), a plain job only runs when
    a connected trigger (webhook / cron) enqueues it. Maps to the framework
    lexigram-tasks ``@task`` decorator.

    Attributes:
        name: snake_case task identifier (module/function stem).
        enabled: When False the job is generated but never enqueued.
        description: Human-readable docstring for the generated task.
    """

    name: str
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ServiceConfig:
    """A service node: business logic for an entity, generated by the
    framework lexigram-sql ``service`` generator.

    The generated ``<Name>Service`` wraps the SQL unit of work (atomic
    writes) and the database provider (reads) with create/get/list/delete
    methods, and is bound in DI so controllers/handlers can resolve it.

    Attributes:
        name: snake_case service identifier. When wired to an entity this
            defaults to that entity's name so the generated ``<Name>Service``
            matches the table.
        enabled: When False the service is generated but not bound in DI.
        description: Human-readable docstring for the generated service.
    """

    name: str
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class SeederConfig:
    """A seeder node: idempotent seed data for an entity, generated by the
    framework lexigram-sql ``seeder`` generator.

    Each generated seeder exposes ``async def run(provider)`` that inserts
    sample rows only when the table is empty; the DI persistence provider
    runs it once after migrations on boot.

    Attributes:
        name: snake_case seeder identifier. When wired to an entity this
            defaults to that entity's name so the seeder matches the table.
        enabled: When False the seeder is generated but not run at boot.
        description: Human-readable docstring for the generated seeder.
    """

    name: str
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ExceptionFilterConfig:
    """An exception-filter node: maps a raised exception to a structured
    HTTP response, generated by the framework lexigram-web
    ``exception_filter`` generator.

    The generated ``<Name>ExceptionFilter`` (an
    ``ExceptionFilterProtocol`` with ``can_handle`` / ``handle``) is added to
    the web layer's global filter pipeline at boot, so matching exceptions
    become JSON responses instead of unhandled 500s.

    Attributes:
        name: snake_case identifier (file/class stem).
        exception_type: Exception class name the filter matches (e.g.
            ``ValueError``).
        status_code: HTTP status the filter responds with.
        enabled: When False the filter is generated but not registered.
        description: Human-readable docstring for the generated filter.
    """

    name: str
    exception_type: str = "ValueError"
    status_code: int = 400
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class CacheConfig:
    """A cache node: cache-aside repository for an entity, generated by the
    framework lexigram-cache ``cache_repo`` generator.

    The generated ``<Name>Repository`` wraps an underlying
    ``RepositoryProtocol`` with a transparent cache layer (reads probe the
    cache first; writes invalidate affected keys). It is backed by the
    framework ``CacheService``, which the app provides via ``CacheModule``.

    Attributes:
        name: snake_case identifier. When wired to an entity this defaults
            to that entity's name.
        ttl: Cache time-to-live in seconds (default 300).
        enabled: When False the cache is generated but not wired.
        description: Human-readable docstring for the generated repository.
    """

    name: str
    ttl: int = 300
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class GraphQLConfig:
    """A GraphQL node: a Strawberry schema module for an entity, generated by
    the framework lexigram-graphql ``graphql`` generator.

    The generated ``<Name>.py`` declares a Strawberry ``@strawberry.type``
    Query/Mutation pair plus relay connection and CRUD input types, and a
    module-level ``schema``. The app wires ``GraphQLModule`` so the schema is
    served at ``/graphql``. Resolver bodies are TODO stubs the developer wires
    to the entity's service.

    Attributes:
        name: snake_case entity stem. When wired to an entity this defaults to
            that entity's name.
        enabled: When False the schema is generated but the module is omitted.
        description: Human-readable note.
    """

    name: str
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class HealthConfig:
    """A health-check node: an observability ``HealthCheck`` for an entity,
    generated by the framework lexigram-monitor ``health`` generator.

    The generated ``<Name>HealthCheck(HealthCheck)`` reports liveness for the
    entity's dependency; the app wires ``MonitorModule`` which serves the
    ``/health`` endpoint. The framework does not auto-discover standalone
    check classes (they must be registered on the ``HealthCheckerRegistry``
    at boot), so the generated check is imported on demand.

    Attributes:
        name: snake_case entity stem. When wired to an entity this defaults to
            that entity's name.
        critical: When True a failing check marks the service unhealthy.
        enabled: When False the check is generated but not wired.
        description: Human-readable note.
    """

    name: str
    critical: bool = True
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class EventConfig:
    """A domain-event node: an immutable event published on the event bus,
    generated by the framework lexigram-events ``event`` generator.

    The generated ``<Name>Event(DomainEvent)`` is a frozen dataclass carrying
    a payload plus aggregate context (via a ``build_<name>_event`` helper).
    Producers (entities) emit it and consumers (jobs, webhooks, channels)
    react to it via the async event pipeline.

    Attributes:
        name: Event name in ``snake_case`` (e.g. ``order_created``). The
            generator derives ``<Pascal>Event`` from it.
        payload: ``(field_name, field_type)`` pairs carried by the event.
        enabled: When False the event is modeled but not emitted.
        description: Human-readable note / docstring.
    """

    name: str
    payload: tuple[tuple[str, str], ...] = ()
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class EventHandlerConfig:
    """An event-handler node: an in-process subscriber that reacts to a domain
    event on the event bus, generated by the framework lexigram-events
    ``event_handler`` generator.

    Unlike a ``job`` (which runs on the out-of-process task queue), an event
    handler is invoked synchronously by the in-process ``EventBusProtocol`` for
    side effects (emails, projections, cache invalidation). The generated
    ``<Name>Handler`` exposes an ``on_<event>`` method; a late-boot provider
    subscribes it to the resolved event type.

    Attributes:
        name: Handler name in ``snake_case`` (e.g. ``send_order_confirmation``).
        event: The event name/type this handler subscribes to (snake_case).
        enabled: When False the handler is generated but not subscribed.
        description: Human-readable note / docstring.
    """

    name: str
    event: str = ""
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class CqrsMessageConfig:
    """A CQRS command or query node, generated by the framework
    lexigram-events ``command`` / ``query`` generators.

    Each generator emits one module containing the frozen message
    dataclass (``<Pascal>Command`` / ``<Pascal>Query``), a result type,
    and the handler (``<Pascal>Handler`` implementing
    ``CommandHandlerProtocol`` / ``QueryHandlerProtocol``). Handlers are
    registered explicitly on the matching bus
    (``CommandBusProtocol`` / ``QueryBusProtocol`` — both already bound
    by ``EventsModule``); the framework has no handler auto-discovery.

    An ``entity -> command|query`` edge binds the handler to that
    entity's repository (the write-side repo for commands, the read
    model for queries).

    Attributes:
        name: Message name in ``snake_case`` (e.g. ``create_order``).
        side: ``"command"`` (write intent) or ``"query"`` (read intent).
        entity: The wired aggregate/entity name (filled from the edge;
            used to inject ``<Pascal>Repository``).
        fields: Message payload ``(field_name, field_type)`` pairs.
        enabled: When False nothing is generated or registered.
        description: Human-readable note / docstring.
    """

    name: str
    side: str = "command"
    entity: str = ""
    fields: tuple[tuple[str, str], ...] = ()
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ProjectionConfig:
    """A read-model projection node, generated by the framework
    lexigram-events ``projection`` generator.

    A projection subscribes to one or more domain events and updates a
    read-optimized view (CQRS read side). The generated
    ``<Name>Projection(ProjectionProtocol)`` is registered with a
    ``ProjectionManager`` at boot; the manager is subscribed on the event
    bus so each published event is dispatched to the projections whose
    ``handles`` set includes its type.

    An ``event -> projection`` edge decides which events the projection
    consumes (the generator emits an empty ``handles`` set; the playground
    reconciler fills it from the wired events).

    Attributes:
        name: Projection name in ``snake_case`` (e.g. ``orders_view``).
        events: Subscribed event names (filled from wired event nodes).
        enabled: When False nothing is generated or registered.
        description: Human-readable note / docstring.
    """

    name: str
    events: tuple[str, ...] = ()
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class SagaConfig:
    """A saga orchestrator node (lexigram-events ``saga`` generator)."""

    name: str
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class MetricConfig:
    """An application metric node, generated by the framework
    lexigram-monitor ``metric`` generator.

    The generator emits a frozen ``<Name>Metric`` dataclass whose
    ``record()`` method forwards observations to the monitoring backend
    (resolved from the container); it is a user-edited scaffold, like a
    domain error, and needs no runtime registration — the presence of the
    node ensures ``MonitorModule`` is configured so
    ``MetricsProtocol`` can be resolved.

    Attributes:
        name: Metric name in ``snake_case`` (e.g. ``orders_placed``).
        unit: Observation unit rendered in the scaffold (``count``,
            ``ms``, ``bytes`` …).
        enabled: When False nothing is generated.
        description: Human-readable note / docstring.
    """

    name: str
    unit: str = "count"
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ApiClientConfig:
    """Outbound HTTP client (lexigram-http ``api_client`` generator)."""

    name: str
    base_url: str = "https://api.example.com"
    auth_type: str = "apikey"
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class StorageDriverConfig:
    """Custom blob storage backend (lexigram-storage ``storage_driver``)."""

    name: str
    driver_type: str = "custom"
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ErrorConfig:
    """An HTTP error node: a domain ``HTTPError`` subclass, generated by the
    framework lexigram-web ``error`` generator.

    The generated ``<Name>Error(HTTPError)`` carries a status code and error
    code; controllers/services raise it and the built-in exception pipeline
    turns it into an RFC 7807 JSON response. It is self-contained (no DI
    wiring) and is imported on demand.

    Attributes:
        name: snake_case identifier (file/class stem). When wired to an
            entity this defaults to that entity's name.
        status_code: HTTP status the raised error responds with.
        error_code: Machine-readable error code (e.g. ``ORDER_NOT_FOUND``).
        enabled: When False the error is generated but not used.
        description: Human-readable docstring for the generated error.
    """

    name: str
    status_code: int = 400
    error_code: str = ""
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ChannelConfig:
    """A realtime channel node: a WebSocket endpoint clients connect to.

    Maps to the framework lexigram-web ``websocket`` generator (an
    ``AbstractWebSocketHandler`` subclass decorated with
    ``@websocket_handler``). The generated handler is registered as a
    container singleton and its ``WebSocketRoute`` is mounted at boot — the
    framework does not auto-discover standalone handler classes (see WS-1 in
    docs/LEXIGRAM_FRAMEWORK_BUGS.md).

    Attributes:
        name: snake_case identifier (module/handler stem).
        path: WebSocket path the channel is mounted at (e.g. ``/ws/chat``).
            Defaults to ``/ws/<name>`` when empty.
        description: Human-readable docstring for the generated handler.
        enabled: When False the channel is generated but not mounted.
    """

    name: str
    path: str = ""
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class AuthConfig:
    """An auth-provider node: the identity scheme guarding wired routes.

    Emission (Workstream B in docs/BACKEND_FRAMEWORK_PLANS.md) is split by
    what the framework already supports:

    * one ``<Name>AuthGuard`` definition module per node (the framework
      lexigram-auth ``auth_guard`` generator — a credential-check scaffold);
    * ``@require_auth()`` decorators applied to the controller handlers of
      every route wired to the node (``lexigram.auth.web`` decorators).

    The decorators enforce authentication on the guarded endpoints; the
    credential check itself is completed by the developer (or a later
    AuthModule wiring) — until an upstream middleware populates
    ``request.state.user``, guarded endpoints reject with 401 by design
    (fail closed).

    Attributes:
        name: snake_case identifier (file/class stem, e.g. ``jwt_auth``).
        provider: Identity provider family (jwt, session, api_key, …).
        login_path: Login endpoint the provider mounts (documented only).
        refresh_token: Whether refresh tokens are part of the scheme.
        token_expiry: Default token lifetime (documented only).
        description: Human-readable note / docstring.
    """

    name: str
    provider: str = "jwt"
    login_path: str = "/auth/login"
    refresh_token: bool = True
    token_expiry: str = "30m"
    description: str = ""


@dataclass(frozen=True, slots=True)
class RoleConfig:
    """A role node: an RBAC role wired to routes via ``route -> role`` edges.

    Emission mirrors :class:`AuthConfig`: one ``<Name>Guard`` definition
    module per node (the framework lexigram-auth ``guard`` generator,
    ``type="role"`` — a RoleGuard subclass scaffold) plus
    ``@require_roles(...)`` decorators on the guarded routes' controller
    handlers. A ``role -> auth`` edge records that the role depends on the
    auth provider; it does not itself guard anything (the role's routes are
    already decorated, and role checks imply authentication).

    Attributes:
        name: snake_case role name (the string ``require_roles`` checks).
        permissions: Flattened ``resource.action`` permission strings
            (parsed from the frontend's per-resource permission objects).
        inherits: Parent role names (documented in the generated scaffold).
        is_default: Whether new users receive this role by default.
        description: Human-readable note / docstring.
    """

    name: str
    permissions: tuple[str, ...] = ()
    inherits: tuple[str, ...] = ()
    is_default: bool = False
    description: str = ""


@dataclass(frozen=True, slots=True)
class RateLimitConfig:
    """A rate-limit node: a throttling policy attached to routes.

    Enforcement is builder-side (nodes plan N2.2): generation emits the
    ``<name>_rate_limit.py`` policy module declaring the strategy/window/max
    constants and the guarded paths, plus an ``app/middleware/rate_limit.py``
    that throttles matching requests (429 + Retry-After once the budget is
    exhausted).

    Attributes:
        name: snake_case identifier (module stem).
        strategy: fixed_window | sliding_window | token_bucket.
        window_seconds: Sliding/fixed window size in seconds.
        max_requests: Requests allowed per window.
        key_by: Throttle key (ip, user, api_key, custom).
        description: Human-readable note / docstring.
    """

    name: str
    strategy: str = "fixed_window"
    window_seconds: int = 60
    max_requests: int = 60
    key_by: str = "ip"
    description: str = ""


@dataclass(frozen=True, slots=True)
class FeatureFlagConfig:
    """A feature-flag node: a canonical flag definition, generated by the
    framework lexigram-features ``feature_flag`` generator.

    The generated ``<Name>Flag`` is a frozen dataclass declaring the flag's
    canonical ``key`` and default rollout so the whole application imports
    one definition. The app registers ``FeatureFlagsModule`` when at least
    one flag exists, so the ``FlagManager``/``FlagProviderProtocol`` are
    resolvable and the flag can be evaluated (env/cache providers) at
    runtime. Endpoint gating is a documented TODO (v2): applying the
    ``@feature_flag`` decorator to a route's handlers needs a controller
    template change upstream.

    Attributes:
        name: snake_case flag identifier (e.g. ``new_checkout``). The
            generator derives ``<Pascal>Flag`` and the ``key`` from it.
        enabled: When False the flag module is not generated and the
            module is not registered.
        description: Human-readable note / docstring.
    """

    name: str
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class SearchIndexConfig:
    """A search-index node: full-text search over one entity's rows.

    Emission is builder-side (nodes plan N3.2), wired via the
    ``entity -> search_index`` edge (the config's ``entity`` field is
    documentation):

    - ``migrations/versions/`` gains a chained alembic revision creating the
      SQLite FTS5 virtual table ``<table>_fts`` plus sync triggers (engine
      ``fts``). ``like`` skips the migration and emits a LIKE-based repo;
      external engines (meilisearch/elasticsearch) are not backend-backed
      yet and fall back to LIKE with an honest module note.
    - ``src/app/repositories/<entity>_search_repository.py`` — an
      ``<Entity>SearchRepository`` (FTS5 ``MATCH`` + bm25 boost weights, or
      LIKE fallback) exposed at ``GET <route>/search?q=&limit=`` through an
      ``<Entity>SearchController``.

    ``fuzzy`` / ``suggestions`` are reserved knobs: v1 does not emit
    different code for them (documented in the module docstring).

    Attributes:
        name: snake_case identifier.
        entity: Optional snake_case entity name (documentation; the wire
            edge is the source of truth).
        fields: Entity field names to index (FTS columns).
        engine: like | fts | meilisearch | elasticsearch (v1 emits
            fts natively, like natively, others fall back to like).
        boost: field -> weight (bm25 column weights; higher ranks stronger).
        fuzzy: Reserved for v1.x (no emission effect yet).
        suggestions: Reserved for v1.x (no emission effect yet).
        enabled: When False nothing is emitted.
        description: Free-text notes surfaced in the inspector.
    """

    name: str
    entity: str = ""
    fields: tuple[str, ...] = ()
    engine: str = "fts"
    boost: dict[str, float] | None = None
    fuzzy: bool = False
    suggestions: bool = False
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ValidatorConfig:
    """A validator node: reusable field-level constraints for an entity.

    Standalone constraint sets (nodes plan N3.1, open question 7's default):
    generation emits ``src/app/validators/<entity>.py`` declaring
    ``<ENTITY>_CONSTRAINTS`` — a field → Pydantic ``Field`` kwargs mapping —
    plus ``validate_<entity>_payload(data) -> dict[str, str]``. Composing
    these into contract models is a documented stretch goal, not v1.
    Supported kwargs: ge, le, gt, lt, min_length, max_length, pattern,
    multiple_of (numeric values parse as int when integral, else float;
    ``pattern`` stays a regex string).

    Attributes:
        name: snake_case identifier.
        entity: Optional snake_case entity name (documentation; the wire
            ``entity -> validator`` edge is the source of truth).
        rules: ``(field, constraint_expr)`` pairs, e.g. ``("price", "ge=0")``.
        enabled: When False nothing is emitted.
        description: Free-text notes surfaced in the inspector.
    """

    name: str
    entity: str = ""
    rules: tuple[tuple[str, str], ...] = ()
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ThumbnailSize:
    """One thumbnail dimension (reserved knob — see FileUploadConfig)."""

    width: int = 256
    height: int = 256
    fit: str = "cover"


@dataclass(frozen=True, slots=True)
class FileUploadConfig:
    """A file-upload node: upload handling for one route (nodes plan N3.3).

    Emission is builder-side, wired via the ``route -> file_upload`` edge
    (the config's ``route`` field is documentation):

    - ``src/app/uploads/<name>_upload_storage.py`` — an
      ``<Pascal>UploadStorage`` service (local-disk v1) that runs the
      framework's ``FileUploadPipeline`` (size + MIME/extension validators)
      and saves files under ``directory`` with generated names
      (path-traversal safe via ``FileUpload.save_to``).
    - ``src/app/controllers/<name>_upload_controller.py`` — a
      ``POST <route>/upload`` endpoint parsing the multipart form
      (``file`` field) through the storage service.

    ``storage`` values ``s3`` / ``gcs`` / ``azure_blob`` are not
    backend-backed yet and fall back to local disk with an honest module
    note (mirrors search-index external engines). ``generate_thumbnails``
    and ``thumbnail_sizes`` are reserved knobs: v1 does not emit thumbnail
    generation (documented in the module docstring).

    Attributes:
        name: snake_case identifier.
        route: Optional snake_case route name (documentation; the wire
            edge is the source of truth).
        storage: local | s3 | gcs | azure_blob (v1 emits local natively;
            others fall back to local with a note).
        max_size: Human-readable cap (``"5MB"``) enforced by
            FileSizeValidator.
        allowed_types: MIME types (``image/png``), wildcards
            (``image/*``) or extensions (``.pdf``); empty disables the
            type gate (validated: an enabled upload needs at least one).
        directory: Relative directory files are stored under.
        generate_thumbnails: Reserved for v1.x (no emission effect yet).
        thumbnail_sizes: Reserved for v1.x (no emission effect yet).
        enabled: When False nothing is emitted.
        description: Free-text notes surfaced in the inspector.
    """

    name: str
    route: str = ""
    storage: str = "local"
    max_size: str = "5MB"
    allowed_types: tuple[str, ...] = ()
    directory: str = "uploads"
    generate_thumbnails: bool = False
    thumbnail_sizes: tuple[ThumbnailSize, ...] = ()
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class ContractConfig:
    """A contract node: a user-shaped request/response payload schema.

    The framework has **no DTO/contract generator** (Workstream C in
    docs/BACKEND_FRAMEWORK_PLANS.md), so the builder emits a Pydantic
    module ``src/app/contracts/<name>.py`` declaring ``<Pascal>Request``
    and/or ``<Pascal>Response`` models from the declared fields. Routes
    wired to the contract (``route_to_contract`` edges) use those models
    in their handlers instead of the entity's auto-derived
    ``<Entity>Create``/``<Entity>Update`` DTOs.

    Attributes:
        name: snake_case identifier (module stem, e.g. ``create_order``).
        direction: request | response | both — which models to emit and
            which handler positions to swap.
        fields: (name, type) pairs in the same grammar as entity fields
            (types validated against palette FIELD_TYPES).
        entity: Optional snake_case entity name this contract shapes
            (documentation + future field reuse; does not change v1
            emission, which is fields-driven).
        enabled: When False the contract module is not generated and the
            wired controllers keep the auto-derived DTOs.
        description: Human-readable note / model docstring.
    """

    name: str
    direction: str = "both"
    fields: tuple[tuple[str, str], ...] = ()
    entity: str = ""
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class GraphNode:
    """A canvas node."""

    id: str
    kind: str
    position: Position
    config: NodeConfig | None


@dataclass(frozen=True, slots=True)
class GraphEdge:
    """A typed canvas edge."""

    id: str
    src: str
    dst: str


@dataclass(frozen=True, slots=True)
class GraphDocument:
    """The source-of-truth canvas document."""

    version: int
    nodes: tuple[GraphNode, ...]
    edges: tuple[GraphEdge, ...]


@dataclass(frozen=True, slots=True)
class ValidatedGraph:
    """A graph that passed validation, with kind-filtered accessors."""

    document: GraphDocument

    def settings(self) -> GraphNode:
        """Return the single app_settings node."""
        return next(n for n in self.document.nodes if n.kind == "app_settings")

    def entities(self) -> list[GraphNode]:
        """Return all entity nodes in document order."""
        return [n for n in self.document.nodes if n.kind == "entity"]

    def routes(self) -> list[GraphNode]:
        """Return all route nodes in document order."""
        return [n for n in self.document.nodes if n.kind == "route"]


@dataclass(frozen=True, slots=True)
class ApiKeyPermission:
    """One permission row of an api_key_group (nodes plan N4.2).

    Attributes:
        resource: snake_case resource name the group may act on.
        actions: Action names granted on the resource (e.g. list/get/create).
        scopes: Extra opaque scope strings granted alongside the actions.
    """

    resource: str
    actions: tuple[str, ...] = ()
    scopes: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class ApiKeyGroupConfig:
    """An api_key_group node: a managed API-key family (nodes plan N4.2).

    Stays screen-managed (the Security modal) — never canvas-draggable — but
    generation now emits real lexigram-auth plumbing when at least one group
    is enabled:

    - a chained alembic revision creating the ``api_keys`` table (the exact
      row shape ``APIKeyManager`` reads: ``id``, ``name``, ``key_hash``,
      ``prefix``, ``user_id``, ``scopes`` JSON, ``expires_at``, ``revoked_at``,
      ``last_used_at``, ``last_used_ip``, ``created_at``, ``updated_at``);
    - ``src/app/repositories/api_key_repository.py`` — a
      ``SqliteApiKeyRepository`` implementing the framework's
      ``APIKeyRepositoryProtocol`` over the database provider;
    - ``src/app/auth/api_keys.py`` — the group's constants (header, prefix,
      flattened ``resource:action`` scopes) plus a ``build_authenticator``
      factory wiring ``APIKeyAuthenticator``/``APIKeyManager``.

    The first enabled group defines header/prefix; permission scopes are
    unioned across all enabled groups. ``rate_limit`` and ``expires_at`` are
    reserved v1 knobs: parsed/validated, no emission effect yet.

    Attributes:
        name: snake_case identifier.
        description: Human-readable note.
        key_prefix: Key family prefix baked into generated raw keys
            (e.g. ``pk_live_``).
        key_header: HTTP header carrying the key (default ``X-API-Key``).
        rate_limit: Reserved for v1.x (no emission effect yet).
        permissions: (resource, actions, scopes) grants for the group.
        expires_at: Reserved for v1.x (default key expiry; no emission yet).
        enabled: When False nothing is emitted.
    """

    name: str
    description: str = ""
    key_prefix: str = "pk_live_"
    key_header: str = "X-API-Key"
    rate_limit: str = ""
    permissions: tuple[ApiKeyPermission, ...] = ()
    expires_at: str = ""
    enabled: bool = True


@dataclass(frozen=True, slots=True)
class EmailVariable:
    """One merge variable of an email_template (nodes plan N4.3).

    Attributes:
        name: snake_case identifier; becomes a constructor parameter of
            the emitted ``Mailable`` subclass and a ``{{name}}`` placeholder
            in the templates.
        type: Declared field type (informative; rendered values are text).
        required: Whether the variable must be supplied.
        default: Optional default value used when the variable is omitted.
    """

    name: str
    type: str = "str"
    required: bool = True
    default: str | None = None


@dataclass(frozen=True, slots=True)
class EmailTemplateConfig:
    """An email_template node: one transactional email (nodes plan N4.3).

    Stays screen-managed (the Emails modal) — never canvas-draggable — but
    generation now emits a real ``Mailable`` per enabled template:

    - ``src/app/emails/<name>_email.py`` — ``<Pascal>Email(Mailable)``
      subclass whose constructor takes the declared merge variables and
      whose ``to_message()`` renders the ``{{var}}`` placeholders of the
      configured subject/HTML/text templates (HTML values are escaped);
    - ``src/app/emails/mailer.py`` — a ``build_mailer()`` factory returning
      the framework's ``ConsoleMailer`` (default) or an env-configured
      ``SMTPMailer``;
    - ``src/app/emails/__init__.py`` — exports of the emitted modules.

    Delivery wiring (who calls ``build_mailer().send(...)`` and when a
    trigger fires) is a v1.x concern: ``triggers`` is parsed and validated
    as documentation but no controller/task hooks are emitted yet.

    Attributes:
        name: snake_case identifier (module + class basename).
        subject: Subject line; may contain ``{{var}}`` placeholders.
        from_email: Sender address (wire key ``from``).
        reply_to: Optional reply-to address (wire key ``replyTo``).
        html_template: HTML body; ``{{var}}`` placeholders are substituted
            with HTML-escaped values.
        text_template: Optional plain-text body (wire key ``textTemplate``).
        variables: Declared merge variables.
        triggers: Free-form documentation of when the email fires.
        enabled: When False nothing is emitted.
        description: Human-readable note.
    """

    name: str
    subject: str = ""
    from_email: str = ""
    reply_to: str = ""
    html_template: str = ""
    text_template: str = ""
    variables: tuple[EmailVariable, ...] = ()
    triggers: tuple[str, ...] = ()
    enabled: bool = True
    description: str = ""


@dataclass(frozen=True, slots=True)
class AuditLogConfig:
    """An audit_log node: a change trail for one entity (nodes plan N4.1).

    Entity-attached via an ``entity -> audit_log`` edge (the config's
    ``entity`` field is documentation). Graduated from the inert nine:
    generation now emits, per wired entity,

    - ``migrations/versions/`` gains a chained alembic revision creating the
      ``<table>_audit_log`` table (``entity_id``, ``op``, ``payload`` JSON,
      ``created_at``) plus an entity_id lookup index;
    - ``src/app/repositories/<entity>_audit_repository.py`` — an
      ``<Entity>AuditRepository`` (``record_created`` / ``record_updated`` /
      ``record_deleted`` / ``list_for``) running raw SQL through the database
      provider, bound in the app's DI persistence provider;
    - a lightweight write hook in the reconciled CRUD controller: wired
      ``create`` / ``update`` / ``delete`` handlers append one audit call
      recording ``entity_id, op, payload``.

    ``capture_request_meta`` and ``retention_days`` are reserved v1 knobs:
    they are parsed and validated but have no emission effect yet (documented
    in TASKS.md and the emitted repository docstring).

    Attributes:
        name: snake_case identifier.
        entity: Optional snake_case entity name (documentation; the wire
            edge is the source of truth).
        operations: Which CRUD mutations to audit (subset of
            create/update/delete; reads are never audited).
        capture_fields: When non-empty, persist only these payload keys;
            when empty, persist the full payload minus ``exclude_fields``.
        exclude_fields: Payload keys redacted before persisting (applied
            recursively in the emitted repository).
        capture_request_meta: Reserved for v1.x (no emission effect yet).
        retention_days: Reserved for v1.x (no pruning job is emitted yet).
        enabled: When False nothing is emitted.
        description: Human-readable note surfaced in the inspector.
    """

    name: str
    entity: str = ""
    operations: tuple[str, ...] = ("create", "update", "delete")
    capture_fields: tuple[str, ...] = ()
    exclude_fields: tuple[str, ...] = ("password", "token")
    capture_request_meta: bool = False
    retention_days: int = 90
    enabled: bool = True
    description: str = ""


NodeConfig = (
    AppSettingsConfig
    | EntityConfig
    | RouteConfig
    | MiddlewareConfig
    | CronConfig
    | WebhookConfig
    | JobConfig
    | ServiceConfig
    | SeederConfig
    | ExceptionFilterConfig
    | ErrorConfig
    | CacheConfig
    | GraphQLConfig
    | HealthConfig
    | EventConfig
    | EventHandlerConfig
    | CqrsMessageConfig
    | ProjectionConfig
    | MetricConfig
    | SagaConfig
    | ApiClientConfig
    | StorageDriverConfig
    | ChannelConfig
    | FeatureFlagConfig
    | AuthConfig
    | RoleConfig
    | RateLimitConfig
    | ContractConfig
    | ValidatorConfig
    | SearchIndexConfig
    | FileUploadConfig
    | AuditLogConfig
    | ApiKeyGroupConfig
    | EmailTemplateConfig
)
