"""The lazy import map for the ``oridecon.ui`` public surface.

Maps every public name to the module that defines it; ``oridecon.ui``
resolves these on first access via module ``__getattr__``.  Kept in its
own module so the top-level package stays small and import-cheap.
"""

from __future__ import annotations

LAZY_IMPORTS: dict[str, str] = {
    # ---- Core primitives ----
    "Component": "oridecon.ui.core.base",
    "Element": "oridecon.ui.core.base",
    "RawHTML": "oridecon.ui.core.base",
    "el": "oridecon.ui.core.base",
    "raw": "oridecon.ui.core.base",
    "render_to_string": "oridecon.ui.core.base",
    # ---- Context ----
    "UIContext": "oridecon.ui.core.context",
    "get_ui_context": "oridecon.ui.core.context",
    "reset_ui_context": "oridecon.ui.core.context",
    "set_ui_context": "oridecon.ui.core.context",
    # ---- Zones ----
    "Zone": "oridecon.ui.core.zones",
    "Zones": "oridecon.ui.core.zones",
    "SwapMode": "oridecon.ui.core.zones",
    # ---- URL safety ----
    "is_safe_navigation_url": "oridecon.ui.core.url",
    # ---- Script safety ----
    "js_json": "oridecon.ui.core.js",
    "js_string": "oridecon.ui.core.js",
    # ---- Table state ----
    "TableState": "oridecon.ui.state",
    # ---- Table actions ----
    "Action": "oridecon.ui.actions",
    "ActionTarget": "oridecon.ui.actions",
    "BulkAction": "oridecon.ui.actions",
    "CreateAction": "oridecon.ui.actions",
    "DeleteAction": "oridecon.ui.actions",
    "DeleteBulkAction": "oridecon.ui.actions",
    "EditAction": "oridecon.ui.actions",
    "ExportAction": "oridecon.ui.actions",
    "ExportBulkAction": "oridecon.ui.actions",
    "ViewAction": "oridecon.ui.actions",
    # ---- Table columns ----
    "Column": "oridecon.ui.columns",
    "TextColumn": "oridecon.ui.columns",
    "BadgeColumn": "oridecon.ui.columns",
    "BooleanColumn": "oridecon.ui.columns",
    "DateColumn": "oridecon.ui.columns",
    "ImageColumn": "oridecon.ui.columns",
    "CurrencyColumn": "oridecon.ui.columns",
    "ListColumn": "oridecon.ui.columns",
    # ---- Icons ----
    "get_icon": "oridecon.ui.atoms.icons",
    "IconDefinition": "oridecon.ui.atoms.icons",
    "IconLibrary": "oridecon.ui.atoms.icons",
    # ---- HTMX namespaces ----
    "htmx": "oridecon.ui.htmx",
    "helpers": "oridecon.ui.htmx",
    "sse": "oridecon.ui.htmx",
    "HtmxActionResponse": "oridecon.ui.htmx.action_response",
    "HTMXAttrs": "oridecon.ui.htmx.table_attrs",
    "HTMXAttrsBuilder": "oridecon.ui.htmx.table_attrs",
    # ---- Exceptions & errors ----
    "UIError": "oridecon.ui.exceptions",
    "ErrorCategory": "oridecon.ui.exceptions",
    "FieldError": "oridecon.ui.exceptions",
    "ErrorResponse": "oridecon.ui.exceptions",
    "validation_error": "oridecon.ui.exceptions",
    "not_found_error": "oridecon.ui.exceptions",
    "permission_error": "oridecon.ui.exceptions",
    "server_error": "oridecon.ui.exceptions",
    "timeout_error": "oridecon.ui.exceptions",
    "render_validation_errors": "oridecon.ui.exceptions",
    "htmx_error_response": "oridecon.ui.exceptions",
    # ---- DI ----
    "UIModule": "oridecon.ui.module",
    "UIProvider": "oridecon.ui.di.provider",
    # ---- Protocols ----
    "RenderableProtocol": "oridecon.ui.protocols",
    # ---- Decorators ----
    "component": "oridecon.ui.decorators",
    # ---- Hooks ----
    "UIComponentRenderedHook": "oridecon.ui.hooks",
    "UITemplateRenderedHook": "oridecon.ui.hooks",
    # ---- Accessibility ----
    "AriaAttrs": "oridecon.ui.accessibility",
    "AriaLive": "oridecon.ui.accessibility",
    "AriaRole": "oridecon.ui.accessibility",
    "SkipLink": "oridecon.ui.accessibility",
    "announce": "oridecon.ui.accessibility",
    "announce_action_complete": "oridecon.ui.accessibility",
    "announce_selection_change": "oridecon.ui.accessibility",
    "announce_table_update": "oridecon.ui.accessibility",
    "button_aria": "oridecon.ui.accessibility",
    "cell_aria": "oridecon.ui.accessibility",
    "dialog_aria": "oridecon.ui.accessibility",
    "header_aria": "oridecon.ui.accessibility",
    "keyboard_navigation_script": "oridecon.ui.accessibility",
    "live_region_aria": "oridecon.ui.accessibility",
    "row_aria": "oridecon.ui.accessibility",
    "search_aria": "oridecon.ui.accessibility",
    "tab_aria": "oridecon.ui.accessibility",
    "tabpanel_aria": "oridecon.ui.accessibility",
    "table_aria": "oridecon.ui.accessibility",
    # ---- Config ----
    "UIConfig": "oridecon.ui.config",
    "DebounceConfig": "oridecon.ui.config",
    "HTMLDocumentConfig": "oridecon.ui.config",
    "BaseLayoutConfig": "oridecon.ui.config",
    "HeadConfig": "oridecon.ui.config",
    "FooterConfig": "oridecon.ui.config",
    "ToastConfig": "oridecon.ui.config",
    # ---- Atoms — primitives ----
    "Button": "oridecon.ui.atoms.button",
    "SubmitButton": "oridecon.ui.atoms.button",
    "Badge": "oridecon.ui.atoms.badge",
    "Spinner": "oridecon.ui.atoms.spinner",
    "Icon": "oridecon.ui.atoms.icon",
    "Divider": "oridecon.ui.atoms.divider",
    "Link": "oridecon.ui.atoms.link",
    "Label": "oridecon.ui.atoms.label",
    "Fieldset": "oridecon.ui.atoms.fieldset",
    "FileUpload": "oridecon.ui.atoms.file_upload",
    "ProgressBar": "oridecon.ui.atoms.progress_bar",
    "Skeleton": "oridecon.ui.atoms.skeleton",
    "Switch": "oridecon.ui.atoms.switch",
    "Tooltip": "oridecon.ui.atoms.tooltip",
    "MarkdownEditor": "oridecon.ui.atoms.editors",
    "RichEditor": "oridecon.ui.atoms.editors",
    # ---- Atoms — layout primitives ----
    "Aside": "oridecon.ui.atoms.layout",
    "Col": "oridecon.ui.atoms.layout",
    "Container": "oridecon.ui.atoms.layout",
    "Grid": "oridecon.ui.atoms.layout",
    "Row": "oridecon.ui.atoms.layout",
    "Stack": "oridecon.ui.molecules.stack",
    "shadcn_css": "oridecon.ui.styles.theme",
    # ---- Atoms — inputs (base + text) ----
    "AbstractInput": "oridecon.ui.atoms.inputs",
    "Input": "oridecon.ui.atoms.inputs",
    "TextInput": "oridecon.ui.atoms.inputs",
    "PasswordInput": "oridecon.ui.atoms.inputs",
    "EmailInput": "oridecon.ui.atoms.inputs",
    "TextArea": "oridecon.ui.atoms.inputs",
    # ---- Atoms — inputs (numeric & date) ----
    "NumberInput": "oridecon.ui.atoms.inputs",
    "Slider": "oridecon.ui.atoms.inputs",
    "DateInput": "oridecon.ui.atoms.inputs",
    "TimePicker": "oridecon.ui.atoms.inputs",
    # ---- Molecules — table controls ----
    "DateHierarchyFilter": "oridecon.ui.molecules.date_hierarchy",
    "DateRangeFilter": "oridecon.ui.molecules.date_range_filter",
    "DataTableScriptRenderer": "oridecon.ui.molecules.data_table_client_logic",
    "FilterDropdown": "oridecon.ui.molecules.filter_dropdown",
    "InlineEditCell": "oridecon.ui.molecules.inline_edit_cell",
    "JumpToPage": "oridecon.ui.molecules.jump_to_page",
    "PageSizeSelector": "oridecon.ui.molecules.page_size_selector",
    "SearchBar": "oridecon.ui.molecules.search_bar",
    # ---- Molecules — pagination family ----
    "LayoutSwitcher": "oridecon.ui.molecules.layout_switcher",
    "PaginationLinks": "oridecon.ui.molecules.pagination_links",
    "TablePagination": "oridecon.ui.molecules.table_pagination",
    "ViewSwitcher": "oridecon.ui.molecules.view_switcher",
    "SortSwitcher": "oridecon.ui.molecules.sort_switcher",
    "GroupBySwitcher": "oridecon.ui.molecules.group_by_switcher",
    "DensitySwitcher": "oridecon.ui.molecules.density_switcher",
    "ColumnVisibilitySwitcher": "oridecon.ui.molecules.column_visibility_switcher",
    # ---- Molecules — detail widgets ----
    "InfolistEntry": "oridecon.ui.molecules.infolist",
    "InfolistEntryType": "oridecon.ui.molecules.infolist",
    "InfolistWidget": "oridecon.ui.molecules.infolist",
    "Tab": "oridecon.ui.molecules.tab_group",
    "TabGroup": "oridecon.ui.molecules.tab_group",
    # ---- Atoms — inputs (selection) ----
    "Select": "oridecon.ui.atoms.inputs",
    "MultiSelect": "oridecon.ui.atoms.inputs",
    "NativeMultiSelect": "oridecon.ui.atoms.inputs",
    "LazySelect": "oridecon.ui.atoms.inputs",
    "CheckboxList": "oridecon.ui.atoms.inputs",
    "Radio": "oridecon.ui.atoms.inputs",
    "BelongsTo": "oridecon.ui.atoms.inputs",
    "MorphTo": "oridecon.ui.atoms.inputs",
    # ---- Atoms — inputs (toggle) ----
    "Checkbox": "oridecon.ui.atoms.inputs",
    "Toggle": "oridecon.ui.atoms.inputs",
    # ---- Atoms — inputs (special) ----
    "ColorPicker": "oridecon.ui.atoms.inputs",
    "Hidden": "oridecon.ui.atoms.inputs",
    "KeyValueField": "oridecon.ui.atoms.inputs",
    "Rating": "oridecon.ui.atoms.inputs",
    "TagsInput": "oridecon.ui.atoms.inputs",
    # ---- Atoms — inputs (file) ----
    "AvatarUpload": "oridecon.ui.atoms.inputs",
    "MultiFileUpload": "oridecon.ui.atoms.inputs",
    # ---- Action button ----
    "ActionButton": "oridecon.ui.molecules.action_button",
    # ---- Builder ----
    "Builder": "oridecon.ui.molecules.builder",
    # ---- Molecules ----
    "Alert": "oridecon.ui.molecules.alert",
    "SimpleAlert": "oridecon.ui.molecules.simple_alert",
    "Breadcrumbs": "oridecon.ui.molecules.breadcrumbs",
    "Card": "oridecon.ui.molecules.card",
    "Dropdown": "oridecon.ui.molecules.dropdown",
    "EmptyState": "oridecon.ui.molecules.empty_state",
    "ErrorState": "oridecon.ui.molecules.error_state",
    "FormField": "oridecon.ui.molecules.form_field",
    "FieldSchema": "oridecon.ui.molecules.form_field",
    "FormActions": "oridecon.ui.molecules.form_actions",
    "InputGroup": "oridecon.ui.molecules.input_group",
    "LoadingOverlay": "oridecon.ui.molecules.loading_overlay",
    "MetricCard": "oridecon.ui.molecules.metric_card",
    "Modal": "oridecon.ui.molecules.modal",
    "Popover": "oridecon.ui.molecules.popover",
    "RichSelect": "oridecon.ui.molecules.rich_select",
    "Section": "oridecon.ui.molecules.section",
    "StatCard": "oridecon.ui.molecules.stat_card",
    "Tabs": "oridecon.ui.molecules.tabs",
    "TabPanel": "oridecon.ui.molecules.tabs",
    # ---- Molecules — toggle ----
    "ToggleIcon": "oridecon.ui.molecules.toggle",
    # ---- Molecules — toasts ----
    "InlineToast": "oridecon.ui.molecules.toast",
    "ToastData": "oridecon.ui.molecules.toast",
    "ServerToastChannel": "oridecon.ui.molecules.toast",
    "ToastType": "oridecon.ui.molecules.toast",
    "flash_to_toast": "oridecon.ui.molecules.toast",
    # ---- Molecules — realtime / scroll ----
    "InfiniteScrollTrigger": "oridecon.ui.molecules.virtual_scroll",
    "VirtualScroll": "oridecon.ui.molecules.virtual_scroll",
    "RealTimeFeed": "oridecon.ui.molecules.realtime",
    "LiveCounter": "oridecon.ui.molecules.realtime",
    # ---- Organisms ----
    "Form": "oridecon.ui.organisms.forms",
    "Repeater": "oridecon.ui.organisms.repeater",
    "AreaChart": "oridecon.ui.charts",
    "BarChart": "oridecon.ui.charts",
    "ChartConfig": "oridecon.ui.charts",
    "ChartDataPoint": "oridecon.ui.charts",
    "ChartType": "oridecon.ui.charts",
    "LineChart": "oridecon.ui.charts",
    "MiniBar": "oridecon.ui.charts",
    "PieChart": "oridecon.ui.charts",
    "Sparkline": "oridecon.ui.charts",
    "ActivityFeed": "oridecon.ui.organisms.activity_feed",
    "AdminCard": "oridecon.ui.organisms.admin",
    "PageLayout": "oridecon.ui.organisms.admin",
    "SlideOver": "oridecon.ui.organisms.slide_over",
    # ---- Organisms — admin-suite additions ----
    "AutoRefreshWidget": "oridecon.ui.organisms.live_polling",
    "LiveDataTable": "oridecon.ui.organisms.live_polling",
    "NotificationBell": "oridecon.ui.organisms.notification_bell",
    "TaskProgress": "oridecon.ui.organisms.task_progress",
    "UserBox": "oridecon.ui.organisms.userbox",
    "SystemBox": "oridecon.ui.organisms.systembox",
    "SortableRecordList": "oridecon.ui.organisms.sortable_list",
    "FilterDrawer": "oridecon.ui.organisms.filter_drawer",
    "SimplePagination": "oridecon.ui.organisms.simple_pagination",
    # ---- Layouts ----
    "LayoutBase": "oridecon.ui.layouts",
    "BaseLayoutContext": "oridecon.ui.layouts.base_layout",
    "CSSManager": "oridecon.ui.layouts",
    "JSManager": "oridecon.ui.layouts",
    "HTMLDocument": "oridecon.ui.layouts",
    "FooterLink": "oridecon.ui.layouts.footer",
    "FooterRenderer": "oridecon.ui.layouts.footer",
    "HeadRenderer": "oridecon.ui.layouts.head",
    # ---- Performance ----
    "RenderCache": "oridecon.ui.performance.performance",
    "RequestCoalescer": "oridecon.ui.performance.performance",
    "ResponseOptimizer": "oridecon.ui.performance.performance",
    "add_htmx_timing_header": "oridecon.ui.performance.performance",
    "cached_render": "oridecon.ui.performance.performance",
    "debounced_search_attrs": "oridecon.ui.performance.performance",
    "infinite_scroll_trigger": "oridecon.ui.performance.performance",
    "lazy_load_placeholder": "oridecon.ui.performance.performance",
    "measure_render_time": "oridecon.ui.performance.performance",
    "optimize_htmx_response": "oridecon.ui.performance.performance",
    # ---- Observability ----
    "MetricsCollector": "oridecon.ui.performance.observability",
    "MetricProtocol": "oridecon.ui.performance.observability",
    "MetricType": "oridecon.ui.performance.observability",
    # ---- CLI / Registry ----
    "COMPONENT_REGISTRY": "oridecon.ui.cli.registry",
}
