"""Unit tests for request ID middleware"""
from unittest.mock import Mock

import pytest
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Route
from starlette.testclient import TestClient

from lexigram.web.middleware.request_id import (
    RequestIDLogFilter,
    RequestIDMiddleware,
    get_request_id_from_request,
)


def _make_client(header_name: str = "X-Request-ID") -> TestClient:
    """Build a TestClient wrapped by RequestIDMiddleware."""

    async def homepage(request):
        return JSONResponse({"ok": True})

    inner = Starlette(routes=[Route("/", homepage)])
    return TestClient(RequestIDMiddleware(inner, header_name=header_name))


class TestRequestIDMiddleware:
    """Test request ID middleware via the ASGI stack."""

    def test_middleware_injects_request_id(self) -> None:
        """Response includes an X-Request-ID header generated by the middleware."""
        client = _make_client()
        response = client.get("/")
        assert response.status_code == 200
        assert "x-request-id" in response.headers
        assert response.headers["x-request-id"].startswith("req_")

    def test_middleware_uses_existing_request_id(self) -> None:
        """If the request already carries X-Request-ID, the same value is echoed back."""
        client = _make_client()
        response = client.get("/", headers={"X-Request-ID": "existing-id-123"})
        assert response.status_code == 200
        assert response.headers["x-request-id"] == "existing-id-123"

    def test_middleware_custom_header_name(self) -> None:
        """Middleware respects a custom header name."""
        client = _make_client(header_name="X-Trace-ID")
        response = client.get("/")
        assert "x-trace-id" in response.headers
        assert response.headers["x-trace-id"].startswith("req_")

    def test_each_request_gets_unique_id(self) -> None:
        """Two requests without a pre-set ID should receive different IDs."""
        client = _make_client()
        r1 = client.get("/")
        r2 = client.get("/")
        id1 = r1.headers["x-request-id"]
        id2 = r2.headers["x-request-id"]
        assert id1 != id2
        assert id1.startswith("req_")
        assert id2.startswith("req_")

    def test_generated_id_format(self) -> None:
        """Generated ID has the expected 'req_<12 hex chars>' shape."""
        client = _make_client()
        response = client.get("/")
        req_id = response.headers["x-request-id"]
        assert req_id.startswith("req_")
        assert len(req_id) == 16  # "req_" + 12 hex digits

    def test_non_http_scope_passes_through(self) -> None:
        """WebSocket / lifespan scopes are forwarded unchanged."""
        # Lifespan is handled internally by TestClient — we just confirm
        # a standard GET still works, meaning non-http scopes don't crash.
        client = _make_client()
        response = client.get("/")
        assert response.status_code == 200

    def test_middleware_preserves_other_response_headers(self) -> None:
        """Existing response headers are not dropped by the middleware."""
        async def with_headers(request):
            return JSONResponse({"ok": True}, headers={"X-Custom": "value"})

        inner = Starlette(routes=[Route("/", with_headers)])
        client = TestClient(RequestIDMiddleware(inner))
        response = client.get("/")
        assert response.headers.get("x-custom") == "value"
        assert "x-request-id" in response.headers


class TestRequestIDLogFilter:
    """Test request ID log filter."""

    @pytest.fixture
    def ctx(self):
        """Create a default context instance."""
        from lexigram.primitives.context import create_default_context
        return create_default_context()

    @pytest.fixture
    def log_filter(self, ctx) -> RequestIDLogFilter:
        """Create log filter instance with injected context."""
        return RequestIDLogFilter(ctx=ctx)

    def test_filter_adds_request_id_when_present(
        self, log_filter: RequestIDLogFilter, ctx,
    ) -> None:
        """Test that filter adds request ID to log record when present."""
        # Arrange
        from lexigram.primitives.context import REQUEST_ID

        token = ctx.set(REQUEST_ID, "test_request_id")
        try:
            record = Mock()
            record.request_id = None

            # Act
            result = log_filter.filter(record)

            # Assert
            assert result is True  # Should not filter out
            assert record.request_id == "test_request_id"
        finally:
            ctx.registry.resolve_var(REQUEST_ID).reset(token)

    def test_filter_adds_no_request_when_missing(
        self, log_filter: RequestIDLogFilter,
    ) -> None:
        """Test that filter adds 'no_request' when no request ID."""
        # Arrange — no REQUEST_ID set in ctx
        record = Mock()
        record.request_id = None

        # Act
        result = log_filter.filter(record)

        # Assert
        assert result is True
        assert record.request_id == "no_request"


class TestRequestIDUtilities:
    """Test request ID utility functions."""

    def test_get_request_id_from_request_with_id(self) -> None:
        """Test getting request ID from request state."""
        # Arrange
        request = Mock(spec=Request)
        request.state = Mock()
        request.state.request_id = "test_id"

        # Act
        result = get_request_id_from_request(request)

        # Assert
        assert result == "test_id"

    def test_get_request_id_from_request_without_id(self) -> None:
        """Test getting request ID when not set."""
        # Arrange
        request = Mock(spec=Request)

        # Use a real object for state that doesn't have request_id
        class MockState:
            pass

        request.state = MockState()

        # Act
        result = get_request_id_from_request(request)

        # Assert
        assert result is None
